Particular/ServicePulse

- src/ServicePulse.Host/app/js/failed_messages/failedMessages.js
This caused a reconnection event which is shown to the user
> Unsubscribing from a message that we never subscribed to

- src/ServicePulse.Host/app/js/directives/moment.js
- src/ServicePulse.Host/app/js/failed_messages/failedMessages.tpl.html
When an NServiceBus endpoint receives messages from external systems such as BizTalk, TIBCO, etc. directly, the message itself will not contain regular NServiceBus headers. Without them ServiceControl cannot provide all usual information. For example, it won’t be able to determine when message was sent or what is its type.
To ensure that you are able to monitor your endpoints and have valuable metadata from ServiceControl, it becomes important as to how you integrate these messages. If for some reason failed messages will miss some metadata ServicePulse will handle it better by providing more meaningful defaults and descriptions.
Here is an example:
>  Failed messages to display UNKNOWN when data is missing instead of blank or min date

- src/ServicePulse.Host/app/js/app.js
- src/ServicePulse.Host/app/js/custom_checks/customChecks.controller.js
- src/ServicePulse.Host/app/js/dashboard/dashboard.controller.js
- src/ServicePulse.Host/app/js/event_log_items/eventLogItems.js
- src/ServicePulse.Host/app/js/failed_messages/failedMessages.controller.js
- src/ServicePulse.Host/app/js/services/services.stream.js
The $apply call was necessary because we were using a global reference to jQuery instead of injecting and giving angular context. 
I opted to use an internal dictionary per messageType for the subscribers. The subscribe method returns an unsubscribe method, removing the need for $scope references.
> Refactor streamService to not rely on events. Remove apply call with $jquery.

- src/ServicePulse.Host/ServicePulse.Host.csproj
- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/failed_messages/failedMessages.service.js
- src/ServicePulse.Host/app/js/services/services.module.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/services/services.stream.js
- src/ServicePulse.Host/app/js/services/services.uri.js
relates to https://github.com/Particular/ServicePulse/issues/200
If there is a trailing slash on the end of the ServiceControl api uri in the config file ServicePulse would compensate for it inappropriately. Now if the config has a trailing slash or not ServicePulse will be able to handle it.
> If ServiceControl Api Uri is configured with or without a trailing slash the application will now behave properly

- src/ServicePulse.Host/app/js/app.http.js
When trying to switch on the monitoring of an endpoint in the "Endpoints Configuration", the UI updates as if it all succeeds, but if the page is refreshed the monitoring setting resets back to off.
All users of ServiceControl that are currently running v1.11.
It seems when angular sends a PATCH request the `Content-Type` is set to `application/json-patch+json`, this content-type is not recognised by Nancy, hence Nancy is not able to correctly bind to the model and default the flag to `false`.
> Attempt to "switch on" an endpoint in the "Endpoints Configuration" fails

- src/ServicePulse.Host/Nancy/SpecialEmbeddedFileResponse.cs
Connects to https://github.com/Particular/ServicePulse/issues/347
Instead of only doing a case-sensitive load of the resource, try and find a case-insensitive match if the requested case results in no resource found.
Ping @Particular/servicepulse-maintainers
> Perform a case-insensitive lookup for the manifest resource

- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
* Any user of ServicePulse that attempts to browse directly to the `FailedMessages` page without first going to the `FailedGroups` page
An error occurs and the page won't render properly when visiting url /failedMessages without having clicked the ALL FAILED MESSAGES link in the navigation.
[Error when entering /failedMessages page directly](https://github.com/Particular/ServicePulse/issues/358)
Also included are a few code style change.
> Load failed messages if not in local storage

- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
- src/ServicePulse.Host/app/js/views/archive/view.html
- src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
- src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/ServicePulse.Host/app/layout/navbar.html
* Every ServicePulse user that has more than 1000 items in failed queues, endpoints, groups etc.
The lack of formatting makes it hard to read bigger numbers. This change introduce tousand separator to ease the reading
[Number formatting](https://github.com/Particular/ServicePulse/issues/261)
> Adding number formatting using angularjs number filter

- src/ServicePulse.Host/Nancy/SpecialEmbeddedFileResponse.cs
- src/ServicePulse.Host/app/index.html
Servicepulse fails to work on Internet Explorer 11 in intranet environments where IE is configured by group policy to display intranet sites in compatiblity mode. This fix adds an http header to servicepulse to fix this issue for affected browsers.
> Add X-UA-Compatible for Servicepulse

- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.js
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
Connects to https://github.com/Particular/ServicePulse/issues/342
Shows the text "Upgrade to V1.19.0" (or the corresponding version number) when an update to Service Control is available. This matches with the format used in the Service Control Management facility.
Also fixes a bug where the link would not display if Service Pulse was up to date but Service Control was not.
Ping @Particular/servicepulse-maintainers
> Display the version of service control available for upgrade

- src/ServicePulse.Host/Hosting/HostArguments.cs
* Every ServicePulse user that hosts ServicePulse in IIS or any other web server.
When extracting files according to documentation the version number always show 1.2.0 which is incorrect.
[Incorrect version shown when using ServicePulse in IIS](https://github.com/Particular/ServicePulse/issues/371)
cc: @Particular/servicepulse-maintainers please review
> Fix the issue with version when extracting to host in IIS

- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/services/factory.shareddata.js
- src/ServicePulse.Host/app/js/views/pending_retries/controller.js
- src/ServicePulse.Host/app/js/views/pending_retries/view.html
- src/ServicePulse.Host/app/js/views/redirect/edit/controller.js
- src/ServicePulse.Host/app/js/views/redirect/service.js
Bumping the min supported SC version to 1.23.0
Fixing issue with date time zone issues in redirect screen
Replacing text unaudited queue for unaudited endpoint
Hooking to a signalr event to remove message from pending retry screen if displayed
Fixing duplicate error message on create redirect to display queue name
cc: @Particular/servicepulse-maintainers
> Making cosmetic changes to pending retry screen

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/configuration/configuration.html
- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.controller.js
- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.html
- src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
As an outcome of: https://github.com/Particular/ServiceControl/issues/793
@sergioc as we discussed today I renamed mute to dismiss and changed the style to be a button
Please have a look
> Rename mute to dismiss

- src/ServicePulse.Host/app/js/services/factory.shareddata.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
Adds support for displaying groups displayed by different classifications.
Addresses: https://github.com/Particular/ServicePulse/issues/239
Addresses: https://github.com/Particular/PlatformDevelopment/issues/1038
Ping @Particular/servicepulse-maintainers, @janovesk, @mikeminutillo, @SzymonPobiega, @tmasternak, @boblangley
> Allow selection of group classifier

- gitversionconfig.yaml
- src/ServicePulse.Host.Tests/tests/js/views/failed_groups/controller.spec.js
- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/directives/moment.js
- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.js
- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.js
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
- src/ServicePulse.Host/app/js/services/factory.shareddata.js
- src/ServicePulse.Host/app/js/services/service.toast.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/archive/controller.js
- src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
- src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
- src/ServicePulse.Host/app/js/views/event_log_items/eventLogItems.tpl.html
- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/SmokeTest.Client/Program.cs
Support for tracking progress on retry requests performed on failure groups.
Retry requests may take a while to finish. This feature lets Service Pulse users monitor the state and progress of operations initiated, both by them and others. Users can track this across different browser sessions.
Connects to Particular/PlatformDevelopment#936
> Track failure group retry request progress

- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/route.js
Allows for deep linking to failed message groups. This will provide users the ability to bookmark failed groups, or to send links to other people so that they can navigate directly tot he failed groups.
Connects to: https://github.com/Particular/ServicePulse/issues/394
Ping @Particular/servicepulse-maintainers for review.
> Allow deep-linking to failed message groups

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/layout/navbar.html
Connects to https://github.com/Particular/ServicePulse/issues/403
Adds a feedback link to the navbar which opens a link in the github repo.
We could add an issue template too if there is value.
Ping @Particular/servicepulse-maintainers
> Add a feedback link to the navbar

- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
fixes https://github.com/Particular/ServicePulse/issues/408
The minimal changeset required to make SP work from IE 11
It might be even easier to just use `substr` instead of `startsWith` to remove the polyfill again. Thoughts @Particular/servicepulse-maintainers ?
> Fix IE11 compatibility

- src/ServicePulse.Host/app/js/views/message/messages-view.html
Add ServiceInsight tooltip "Browse in ServiceInsight, if installed"
> Add ServiceInsight button tooltip

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/directives/ui.particular.configurationTabs.tpl.html
- src/ServicePulse.Host/app/js/views/configuration/configuration.html
- src/ServicePulse.Host/app/js/views/configuration/configuration.route.js
- src/ServicePulse.Host/app/js/views/redirect/route.js
fixes #392 
Adding labels to make it clear what toggle means. @sergioc please have a look from a UI perspective
> Adding column description to configuration screen

- src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.module.js
* Min value is always 0 based to not cut away areas
* Max value is designed so that the average bar will always show up in case the current data points are smaller than the average (not an issue with the current implementation which calculates average based on the data points, but that will probably change)
the following graph shows how different data points & average values would look like with the current (left) implementation and the proposed changes (right). Each row contains the exact same data on both sides.
> Optimize graph y-axis range

- src/ServicePulse.Host.Tests/tests/js/services/services.monitoring.spec.js
- src/ServicePulse.Host/app/js/services/services.monitoring.js
- src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.html
- src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.module.js
Assumes that the metrics server sends EndpointInstanceIds property down. If the property is missing, no data is shown.
Relies on https://github.com/Particular/ServiceControl.Monitoring/pull/30
> Show instance count

- src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
- src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html
This requires changes from https://github.com/Particular/ServiceControl.Monitoring/pull/37 to work.
This PR introduces retries metric graph to Endpoint List and Endpoint Details pages. Columns on those pages have been made narrower make enough room for new column.
> Retries graph on endpoints list and details pages

- src/ServicePulse.Host/app/js/directives/ui.particular.graph.js
- src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html
This PR removes `plot-x-axis` support from `graph` tag as it's not longer needed after [changes](https://github.com/Particular/ServiceControl.Monitoring/pull/40) to queue-length are applied to `SC.Monitoring`.
> removing plot-x-axis from graph tag

- src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
- src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
- src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html
This PR is part of https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/167 and requires https://github.com/Particular/ServiceControl.Monitoring/pull/54 to work.
It introduces following changes:
* Changes to bindings on list and detail pages adding `metrics.` in metrics bindings - this is result of new generic metrics calculation logic,
* It introduces new section on details page that provides breakdown by message-type
* It introduces 2 tabs for instances and mesasge-type breakdown.
> Metrics breakdown by message type

- src/ServicePulse.Install.CustomActions/CustomAction.cs
- src/Setup/ServicePulse.aip
This PR enables users to run `ServicePulse` installer in feature selection mode. In such case they are able to specify if they want to enable `Recoverability and Auditing` and/or `Monitoring` capabilities.
In order to run the installer in feature selection mode one has to run installer `.exe` with predefined flag:
```
Particular.ServicePulse-1.9.2.exe ENABLE_FEATURE_SELECTION="TRUE"
```
otherwise users will see old configuration dialog. When flag is specified the new configuration dialog is show:
Selection performed by the user on the new configuration page results in changes to `app.constants.js` file. Installer will provide values for `service_control_url` and `monitoring_urls`. In case feature is disabled it will be set to empty string value for `service_control_url` and array of …
> ServicePulse installer with monitoring feature toogle

- src/ServicePulse.Host/bower.json
This adds missing dependency to `bower.json` and should be part of #513.
> Missing moment-duration-format plugin added to bower.json

- src/ServicePulse.Host/app/js/directives/ui.particular.graph.js
This removes `typeof` from the check on undefined property. Otherwise even if the property is undefined the typeof will return string `"undefined"`. As a result `"undefined" !== undefined" will always evaluate to false as `!==` operator does not do type coertion.
> Showing zeros for empty data sets in graphs

- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
- src/ServicePulse.Host/app/js/services/service.formatter.js
- src/ServicePulse.Host/app/js/views/archive/view.html
- Limiting the numbers next to All Failed Message Count and Archived Messages to not include decimal place
- Limiting the numbers in the top menu to not include decimal place
- Limiting the numbers on the button listing amount of selected messages to not include decimal place
- Changing formatter to parse string's into int (it was causing JS error when the value was lower than 1000)
> Fixing small UI Bugs:

- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/app.route.js
This PR enables configuring what is the default route if none is specified. This will be used in monitoring demo but I think it's general enough that we should enable users define starting page if they want to.
> Default route moved to app.constants.js

- src/ServicePulse.Host/package.json
THis allows on dev machine to call 
`npm run setup`
Which now pulls the dependencies and call webpack with watch turned on
> Changing npm scripts to support webpack configuration with watcher

- src/ServicePulse.Host/app/js/services/constant.historyperiods.js
This PR makes the refresh rates smaller on the assumption that SC.Monitoring increases number of intervals for periods bigger than 1 min.
This requires https://github.com/Particular/ServiceControl.Monitoring/pull/72 to work as expected.
> Refresh rates one third smaller

- src/Setup/ServicePulse.aip
The signing certificate is about to expire on December 22. A replacement has been installed on all the build agents. This is the thumbprint for the new one
> Updating signing thumbprint

- src/Setup/ServicePulse.aip
Switches the feature toggle default value from FALSE to TRUE. This will mean that the user does not need to use command line arguments to show the installer URI anymore.
> Default feature selection on

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
This PR changes the way message types are displayed on the endpoint details page. It aligns it with https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/242#issuecomment-334741184.
This requires https://github.com/Particular/ServiceControl.Monitoring/pull/78
> Formatted message types

- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.largeGraph.js
This PR makes sure that yAxis has a fixed height for large graphs with empty data sets.
> Returning constant max yAxis value for empty data series

- src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
- src/ServicePulse.Host/app/layout/navbar.html
Connects to https://github.com/Particular/ServicePulse/issues/563
Stops using a decimal point for things that will be whole numbers only.
Smaller number will show the actual value, larger will be e.g. `25k` instead of `25.3k`
> Stop using decimals for badge counts

- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Currently we are showing `instance.id` on the instance breakdown grid. This does not work as expected when users overrides `HostDisplayName` and does not use `instanceId` argument.
/cc: @danielmarbach
> Show endpoint name instead of id on instace breakdown grid

- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
This PR removes the failed message group links from breakdown tables by message type on monitored endpoint details. This is caused by the fact that current grouping in SC is performed on the basis of `messageType` value. 
This is problematic as different logical endpoints can process the same message type. This can be solved in the future by introducing new groupings in SC that will be based on (endpoint_name, message_type) pairs.
Two endpoints `Shipping` and `Billing` each subscribed to `OrderCreated` event.
> Failed msg group links removed from message type detail table

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Fixes these graph line dips in Endpoint details:
> Fix graph dips

- src/ServicePulse.Host/app/js/views/archive/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/message/controller.js
Fixes the other part of https://github.com/Particular/ServicePulse/issues/628
> Switch from arrow functions

- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
- src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
This is part of Native Queue length implementation. Native ql is not experimental anymore.
> Removed experimental icon from queue length headers

- src/ServicePulse.Host.Tests/SpecsRunner.html
- src/ServicePulse.Host/ServicePulse.Host.csproj
- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/directives/ui.particular.js
- src/ServicePulse.Host/app/js/directives/ui.particular.reindexingStatus.js
- src/ServicePulse.Host/app/js/directives/ui.particular.reindexingstatus.tpl.html
- src/ServicePulse.Host/app/js/services/factory.reindexingChecker.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/archive/view.html
- src/ServicePulse.Host/app/js/views/configuration/configuration.html
- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.html
- src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
- src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/ServicePulse.Host/app/js/views/message/messages-view.html
Connects to https://github.com/Particular/ServiceControl/issues/1144
This change works on all versions of SC so does not require a bump to the minimum version value. If connecting to a version 2 or greater version of ServiceControl it will report if RavenDB is busy re-indexing after a database upgrade.
The check is continual so that SP doesn't have to be refreshed after an upgrade.
> Notify users of long-running reindex processes

- src/ServicePulse.Host/app/js/directives/ui.particular.redirectLink.tpl.html
- src/ServicePulse.Host/app/js/views/archive/view.html
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/ServicePulse.Host/app/js/views/pending_retries/view.html
Fixes https://github.com/Particular/ServicePulse/issues/635
Switches to `#` instead of `javascript://` as Angular 1.7.0 marks those URLs as unsafe.
Because we're now using `#` angular might want to route those to controllers which don't exist, so `$event.preventDefault();` is used to prevent that.
It would make more sense to switch to buttons instead of anchor tags since we don't use the URLs for anything, but the styling changes proved too much for this bug.
> Stop using javascript://

- src/ServicePulse.Host/app/js/views/message/controller.js
- src/ServicePulse.Host/app/js/views/message/messages-view.html
- src/ServicePulse.Host/app/js/views/pending_retries/view.html
Fixes #637 
There are still outsnatnding `javascript:` URLs that result in angular altering the URL to be unsafes. This removes them.
> Remove other javascript: url references

- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.largeGraph.js
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
> Fix graph scaling

- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Addresses: https://github.com/Particular/ServicePulse/issues/654
> Adding no data message when there is no messages processed

- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/ServicePulse.Host/app/layout/navbar.html
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.route.js
- src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.route.js
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
- src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
fixes: https://github.com/Particular/ServicePulse/issues/655
> Change monitoring url

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
fixes: https://github.com/Particular/ServicePulse/issues/445
@sergioc can you have a look on this one. I am not sure if you don't want to move the button a bit
> Adding retry button on one message

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.html
fixes:https://github.com/Particular/ServicePulse/issues/658
Now it looks like this:
> wraping custom check text

- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_groups/view.html
fixes: https://github.com/Particular/ServicePulse/issues/607
> Add storing of group by in URL

- src/ServicePulse.Host/ServicePulse.Host.csproj
- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/directives/ui.particular.js
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
- src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
- src/ServicePulse.Host/app/layout/footer.html
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.monitoringConnectivityStatus.js
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.monitoringConnectivityStatus.tpl.html
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.module.js
- src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.module.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.connectivityNotifier.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
Fixes: https://github.com/Particular/ServicePulse/issues/608
@sergioc please have a look as you might want to style it a bit. It looks good for me, but you might think differently.
@WilliamBZA can you have a look at SC Monitoring connectivity piece from the perspective of using RXjs and from the perspective of integrating toolbar that is part of shell and sc monitoring connectivity that is part of monitoring
> Adding a toolbar that contains SC connectivity status

- src/ServicePulse.Install.CustomActions/CustomAction.cs
- src/ServicePulse.Install.CustomActions/ServicePulse.Install.CustomActions.csproj
- src/Setup/ServicePulse.aip
Solves #573 
The installer queries existing windows services via WMI and searches for `Particular.ServicePulse` which is the name of the installed service. After that, the startup parameters are parsed to extract the port on which the http endpoint is exposed.
> Detect existing ServicePulse port

- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/services/factory.notifier.js
- src/ServicePulse.Host/app/js/views/archive/controller.js
- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/modules/shell/js/licensenotifier/trialexpiring.html
Keeps the connecting screen displayed if a page performs an initial load.
This is opt-in from the controller's perspective. In order to opt in, the controller sets the `performingDataLoadInitially` property on the `serviceControlService` service to true and the publishes an event once the initial load is complete.
The base controller then looks at the `performingDataLoadInitially` property once a view has been rendered to determine whether or not it's ok to remove the connecting screen.
> Display connecting screen while loading

- .gitignore
- src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
- src/ServicePulse.Host.Tests/karma.conf.js
- src/ServicePulse.Host.Tests/package.json
@WilliamBZA after yesterday fix to run-jasmine, I decided that we should eliminate that part of handcrafter TC runner. Given that I introduced karma to run tests. For now I left jasmine as is. When this code gets into master I will change TC config to use karma, and remove old run-jasmine scripts and anything else that we don't need. If for some reason you don't want to pull it into this branch, I can wait with this PR after your feature is done and then do it on master.
> Adding karma as a runner, this is a first step to remove run-jasmine.js

- src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
- src/ServicePulse.Host.Tests/package.json
- src/ServicePulse.Host.Tests/tests/js/views/failed_messages/controller.spec.js
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
Fixes #726 
Adds a flag that can be used to differentiate between an infinite scroll request or a normal request. If the initial load is still being performed and an infinite scroll load happens at the same time, the infinite scroll request is abandoned.
> Differentiate between infinite scroll loads

- src/ServicePulse.Host/ServicePulse.Host.csproj
- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/directives/ui.particular.js
- src/ServicePulse.Host/app/js/services/services.historyperiods.js
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.messageTypesChangeIndicator.js
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.messageTypesChangeIndicator.tpl.html
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.module.js
- src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
- src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
- src/ServicePulse.Host/app/modules/shell/js/services/service.toast.js
- src/ServicePulse.Host/package.json
This PR provides browser-side paging for the message types table in endpoint details view. Specifically, it adds:
* Ordering on message types by message type name,
* Paginator at the bottom of the table,
* Deep linking for page number,
* It does not reload the table automatically when new message types become available but prompt the user to force the view reload,
* loader view for endpoint list and details - useful when there are larger sets of message types
NOTE: this includes updating angular-ui-bootstrap to 2.5.6 in order to get desired behavior of the pager. I've checked the other places we use the package (tooltips and modals) and they look fine after update.
> Handling large number of message type in endpoint details

- src/ServicePulse.Host/app/css/particular.css
1.19 (or an earlier release) broke IE11 support. When the viewport size is smaller than 1400px width the top navbar disappears on IE.
> Restore nav in IE < 1440px

- src/ServicePulse.Host/Commands/ExtractAndUpdateConstantsCommand.cs
- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/app.js
- src/ServicePulse.Host/app/modules/configuration/connectionsManager.js
- src/Setup/ServicePulse.aip
ServicePulse uses the `app.constants.js` file to set default settings. Up to 1.19 the file is an AngularJs module, and thus it requires Angular to be loaded. The new `connectionsManager` on the other hand lives outside AngularJs as it is needed during the bootstrapping process to get license details from ServiceControl.
This PR:
- changes the `app.constants.js` format to be non-Angular dependant
- makes so that the `app.constants.js` simply sets a `window` variable with default configuration values, using the same structure as `1.19` (but outside of AngularJs)
- makes so that the `app.constants.js` is loaded by `Index.html` as first script so that all the dependencies can find the values they expect where they expect them
At install time the installer collects information from the user …
> Add support to migrate existing URLs configuration and re-add support for URLs configuration in the installer

- src/ServicePulse.Host.Tests/ApprovalFiles/APIApprovals.PlatformSampleApprovals.approved.txt
- src/ServicePulse.Host/app/js/app.constants.js
- src/ServicePulse.Host/app/js/app.js
As [stated in the documentation](https://docs.particular.net/servicepulse/intro-pending-retries) by tweaking the `app.constants.js` it should be possible to enable the "show pending retry" feature in ServicePulse. This was broken due to way Pulse was changed to introduce the ability to control che ServiceControl connection. This PR fixes the regression by re-enabling the ability to turn-on the "show pending retry" feature.
> Allow to control (again) the showPendingRetry setting

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/views/message/messages-view.html
Based on feedback this PR adds an explicit link to the original message instead of relying to a link on the `Edited` badge.
> Make the link to the previous version of the edited message explicit

- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/directives/ui.particular.js
- src/ServicePulse.Host/app/js/directives/ui.particular.pageTitleFromRoute.js
- src/ServicePulse.Host/package.json
Fixes https://github.com/Particular/ServicePulse/issues/717
Replaces `ng-page-title` with a custom directive.
Added @WojcikMike as a reviewer in case he want's to look over our work.
> Replace ng-page-title with custom directive

- src/ServicePulse.Host/app/js/views/archive/controller.js
- src/ServicePulse.Host/app/js/views/archive/view.html
- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
Fixes #664 
Fixes #665 
This also addresses another issue where the failed messages and archived messages pages would not load more search results if you managed to remove all displayed items from the list.
> Fix issue with unarchiving more than 50 items at a time

- src/ServicePulse.Host/app/js/views/failed_messages/controller.js
- src/ServicePulse.Host/app/js/views/failed_messages/route.js
- src/ServicePulse.Host/app/js/views/failed_messages/view.html
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Fixes #789 
Not part of the ServicePulse maintenance release but noticed this broken link during testing. The route code I removed because it doesn't appear to be used anywhere else now that the link has been fixed.
> Fix broken link in monitoring endpoint details

- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/modules/modules.webpackconfig.js
- src/ServicePulse.Host/package-lock.json
- src/ServicePulse.Host/package.json
Fixes https://github.com/Particular/ServicePulse/issues/212
Adds a `?v=timestamp` to all js files as part of the webpack build.
Ideally we'd use the webpack chunked hash directly and generate a `dist/index.html`, but this won't cover the files that are not yet in webpack bundles.
We'd also have to change the build pipeline to host the `dist/index.html` file instead of the `/index.html` file.
This PR should cover our needs for a cache-buster, but we should create an issue to update the build to be ready to use a `/dist/index.html` file.
> Prevent cached files from disrupting upgrade process

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
- src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html
Closes https://github.com/Particular/ServicePulse/issues/266
Adds a sort option on the failed message groups.
Adds sort for all the main fields on the group:
* Name
* First failure
* Last failure
* Last retry
* Number of messages
It also saves the sort so that the next time the user views the page it restores the previously selected sort.
> Add sort on failed message groups

- src/ServicePulse.Host.Tests/package-lock.json
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.js
- src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
- src/ServicePulse.Host/app/js/services/services.module.js
- src/ServicePulse.Host/app/layout/footer.html
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.monitoringConnectivityStatus.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
- src/ServicePulse.Host/package-lock.json
- src/ServicePulse.Host/package.json
Adds a check that displays the monitoring version and if there is an upgrade available.
Requires https://github.com/Particular/ServiceControl/pull/1972 to function, but if https://github.com/Particular/ServiceControl/pull/1972 is not merged this gracefully degrades to the current behaviour.
> Add a version check and upgrade link for outdated Monitoring Instances

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/modules/modules.webpackconfig.builder.js
- src/ServicePulse.Host/app/modules/modules.webpackconfig.js
- src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.largeGraph.js
- src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Fixes https://github.com/Particular/ServicePulse/issues/840
Introduces a delete option for stale endpoints.
Sends a HTTP DELETE request to ServiceControl Monitoring to remove the instance from the endpoint registry.
* It first does a Cors OPTIONS check to see if ServiceControl monitoring supports deleting the instances.
* If it returns a header supporting DELETE, then a delete icon will appear when hovering over a stale endpoint instance.
* Clicking on the delete icon will result in the endpoint instance being removed from the Monitoring page.
* If ServiceControl monitoring does not support deleting endpoints, then the behaviour will be exactly as it is now. No changes.
> Allow removal of stale endpoints

- src/ServicePulse.Host/app/index.html
- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.js
- src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
- src/ServicePulse.Host/app/js/services/factory.shareddata.js
- src/ServicePulse.Host/app/js/services/services.service-control.js
- src/ServicePulse.Host/app/js/views/archive/archive-view.html
- src/ServicePulse.Host/app/js/views/archive/controller.js
- src/ServicePulse.Host/app/js/views/archive/service.js
- src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.controller.js
- src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.html
- src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.route.js
- src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.service.js
- src/ServicePulse.Host/package-lock.json
Fixes https://github.com/Particular/ServicePulse/issues/318
Fixes https://github.com/Particular/ServicePulse/issues/801
Requires: https://github.com/Particular/ServiceControl/pull/1987 for the functionality to be seen
Adds an Archive Groups screen.
The screen links to the archived messages screen for that group only.
If ServiceControl does not support Archived Groups, the behaviour is the same as it is now and the user does not notice a difference.
> Add a new "Archive Groups" screen to show groups of archived messages

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
- Number in brackets showing connected instances instead of all known instances.
- Connectivity indicator only shown if there are no connected instances.
- Restored link to instances sub tab on details page on the connectivity indicator.
> Fix behavior of connectivity indicator

- src/ServicePulse.Host/app/css/particular.css
- src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
- Number in brackets showing connected instances instead of all known instances.
- Connectivity indicator only shown if there are no connected instances.
- Restored link to instances sub tab on details page on the connectivity indicator.
> Fixed behavior of connectivity indicator

- src/ServicePulse.Host/app/js/app.controller.js
- src/ServicePulse.Host/app/js/app.js
- src/ServicePulse.Host/app/js/services/services.module.js
- src/ServicePulse.Host/app/layout/navbar.html
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.disconnectedEndpointMonitor.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
- src/ServicePulse.Host/app/modules/monitoring/monitoring.js
This PR adds support for periodically checking the disconnected endpoint count as reported by Monitoring and displaying a badge on the `Monitoring` top navigation menu item.
> Add an endpoint disconnected count to the Monitoring navigation bar item

- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.controller.js
Connected to https://github.com/Particular/ServiceControl/issues/2086
```javascript
var page = 1;
$scope.loadMoreResults = function () {
if ($scope.loadingData) {
return;
}
$scope.loadingData = true;
load(page++);
};
$scope.dismiss = function (row) {
serviceControlService.dismissCustomChecks(row);
};
var notifier = notifyService();
notifier.subscribe($scope, reloadData, 'CustomChecksUpdated');
function reloadData() {
page = 1;
$scope.loadingData = true;
$scope.model = { data: [], total: 0 };
$scope.disableLoadingData = false;
load(page);
}
```
It is possible for `loadMoreResults` to be triggered by the UI (by the infinite scroll) just before the `reloadData` is called via the notification service. In such a case, there are 2 outstanding requests that will both update the list of custom …
> CustomChecks view - infinite scroll and initial load race condition fix

- src/ServicePulse.Host/app/modules/monitoring/views/monitoring_no_data.html
Opens the link of the button on this page on a dedicated browser tab instead of leaving the SP app
> Open docs link in new browser tab

- src/ServicePulse.Host.Tests/tests/js/services/services.messageTypeParser.spec.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.messageTypeParser.js
fixes #970 
"unknown" is shown as messages with a hierarchy don't have a `shortName` property at the moment. Instead of checking for the shortName to exist and fallback to the typeName, it seems more appropriate to also shorten type names on hierarchies too. Replaced the more complex fold with a map/join combination.
> Provide shortened type names on message hierarchies

- src/ServicePulse.Host.Tests/tests/js/services/services.messageTypeParser.spec.js
- src/ServicePulse.Host/app/modules/monitoring/js/services/services.messageTypeParser.js
backport of #976 for `release-1.27` branch.
related to the bug reported in https://github.com/Particular/ServicePulse/issues/970
> Unknown Message Type listed in Monitoring when multiple message types

- src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.html
- src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html
- src/ServicePulse.Host/app/modules/shell/views/events-view.html
There are absolute path references in links that stop the UI from working if hosted in IIS at a non-root location.
> replace absolute paths with relative

- src/ServicePulse.Host/app/js/views/sc_not_available.html
Currently, the string "put here the url we tried to connect to" is displayed as part of the error message that is shown when unable to connect to ServiceControl. This change shows the actual ServiceControlUrl
> Show ServiceControlUrl in error message when unable to connect

- src/ServicePulse.Host/app/css/particular.css
The text is not properly aligned. Here's what it looks like in Chrome before the change:
> Fix text alignment of Dismiss button

- src/ServicePulse.Host/app/js/directives/moment.js
Closes https://github.com/Particular/ServicePulse/issues/271
> Added gmt time

- src/ServicePulse.Host/app/js/views/message/controller.js
From version 1.28 SP is fetching the message body from the Audit instance. If the amount of Audits is big it slows down ServicePulse by doing an expensive calls. This PR is reverting the change.
With this change the message body will once again be pulled from ServiceControl instance
> Remove a duplicated fetching of message headers

- src/ServicePulse.Host/app/js/views/failed_groups/controller.js
https://github.com/Particular/ServicePulse/issues/1054.
There are two places where such notification appears:
- [here: L448](https://github.com/Particular/ServicePulse/blob/hide-completed-notifications/src/ServicePulse.Host/app/js/views/failed_groups/controller.js#L448) - fix applied
- [here: L446](https://github.com/Particular/ServicePulse/blob/hide-completed-notifications/src/ServicePulse.Host/app/js/views/failed_groups/controller.js#L446) - I decided not to touch, because the operation was not 100% completed and I'm not sure if this good idea to automatically hide the notification
In addition (is not applied yet), I propose to fix the behaviour of the notification for deleted groups [here: L421](https://github.com/Particular/ServicePulse/blob/hide-completed-notifications/src/ServicePuls …
> Make some completed toast notification disappear automatically

- src/ServicePulse.Host/app/js/services/services.service-control.js
Fixes #1184
Removes comments of the style:
`// comment`
`/* comment */`
from the body of messages that are received from ServiceControl so that they can be rendered correctly.
This will also remove comments from XML messages as they are sent to SP as JSON anyway and will be subject to the same problems.
I don't know that this is testable given the reliance on angularjs as the `$http` wrapper.
> Strip comments from message body payloads

- src/ServicePulse.Host/app/js/services/services.service-control.js
Fixes https://github.com/Particular/ServicePulse/issues/1194
[Removing the comments from JSON](https://github.com/Particular/ServicePulse/pull/1185) returned by ServiceControl resulted in the result no longer being an object but being text. This PR re-parses the content from the server.
**Before:**
**After:**
_Note that this is parsing data directly from a server. It shouldn't be any more dangerous that what the underlying $http API does_
> Fix JSON payloads not being prettyfied

- src/ServicePulse.Host/app/modules/configuration/views/notificationsemailmodal.html
A customer raised a support ticket stating that account username and password are not saved when configuring email notifications. I can reproduce the issue locally on my machine.
Digging a bit into the entire thing it turns out that the ServiceControl [UpdateEmailNotificationsSettingsRequest](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Notifications/Api/UpdateEmailNotificationsSettingsRequest.cs) expects those value to be in properties named `authorization_account` and `authorization_password`. ServicePulse was binding to `authentication_account` and `authentication_password` causing (if I get it right) the two values to not be stored in ServiceControl.
> Fix property names

- src/ServicePulse.Host/app/js/views/custom_checks/customChecks.html
> Chunk display of metadata for custom checks

- src/ServicePulse.Host/app/index.html
Change ServicePulse pages' description from "An Operations Manager’s Best Friend" to "ServicePulse Monitoring", which is more useful when sharing links in places that show a page's content description instead of title.
> Replace description content

- src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
Unit suffix won't display for processing time and critical time in instances tab of monitoring endpoint details page
> Unit suffix won't display

- src/ServicePulse.Host.Tests/tests/js/services/service.formatter.spec.js
- src/ServicePulse.Host/app/js/services/service.formatter.js
> Timespan sparkline values are incorrectly formatted when displaying minute timespans in "hour" unit values  bug fix

- src/ServicePulse.Host/app/js/services/services.service-control.js
In the last release we added an if, to only prettify json messages when they are in fact json. But we made a mistake by using text/json instead of application/json
Fixes #1272
> Replacing text/json to application/json

- src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js
Checks if connected is already true. If it is true, it means it has successfully connected previously and we don't need to show the loading icon.
Once a connection drops, the connected field is set to false so the next attempt will show the loading icon again.
> Only refresh page if first connection attempt

- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
Refreshes the failed group data every 5 seconds.
We might want to consider decreasing that duration to every 1 second when we detect that a retry is ongoing so that the progress bar responds sooner, but we can improve that as a second step.
> Refresh the failed group data every 5 seconds

- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
Clears the `setInterval` so that the data fetching no longer happens when not on the page
> Stop setInterval from running when not on page

- src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
- src/ServicePulse.Host/vue/src/composables/serviceServiceControlUrls.js
This is related to a support case that was raised about getting a 404 error on the connection and dashboard screens if a trailing `/` is not at the end of the connection strings in the configuration page.
Here is the issue [[2.0] ServicePulse unable to connect to ServiceControl if connection URL lacks a trailing forward slash](https://github.com/Particular/KeepTheLightsOn/issues/1188)
> Adds forward slash to the connection strings if they are missing

- src/ServicePulse.Host/vue/src/components/EventItemShort.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
- src/ServicePulse.Host/vue/src/views/DashboardView.vue
Fix the following links
- Link to angular version of "view all events " from dashboard
- Link to vue version of "Failed messages" from dashboard
- Delete comment note on failed messages group vue
> Fix links in dashboard

- src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue
Highlights the "All [deleted|failed] messages" tabs when clicking through from a group
> Highlight all messages tabs when click through

- src/ServicePulse.Host/vue/src/assets/main.css
Styles the disabled buttons to be more visible
> Style disabled buttons

- src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
Displays 9+ if the retry count is 10.
Fixes https://github.com/Particular/ServicePulse/issues/1366
> Display 9+ for 10 retries

- src/ServicePulse.Host/vue/src/components/failedmessages/FlowDiagram.vue
Takes away the fly in thing, it seems this was intentional but it doesn't actually work in the angular version
> Enter node in the correct place already

- src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupNoteEdit.vue
prevent adding empty note in failed message grps by disabling the create and modify button if the input field is empty
> prevent adding empty note in failed message grps

- src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/PendingRetries.vue
`.replace()` only replaces the first instance, not all 🤦
> Use replaceAll instead of replace

- src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
Changes the polling frequency based on whether or not a retry/delete/restore operation is underway.
Changes from polling every 5 seconds to every second.
> Poll more frequently when operations are underway

- src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
- src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue
The PR addresses the following bugs
- fix the count badge spacing
- All failed message page- disable the checkbox when message is selected for deletion
- All deleted message page- disable the checkbox when message is selected for restore
> Fix badge spacing and disable checkbox on message action

- src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupNoteEdit.vue
Comment should not contain notes with empty spaces
> trim the note before enabling the button

- src/ServicePulse.Host/vue/src/components/EventItemShort.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
This PR replaces the angular failed component links on
- Page header
- Dashboard
> Replace failed messages angular links with vue

- .github/workflows/release.yml
The node options are set during the build and test, but not during the docker files.
> Set node_options in release matrix

- src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
fix "Retry all" and "Delete all" functionality in all failed messages
>  ServicePulse version 1.34.4 and 1.35.0: buttons "Retry all" and "Delete all" do not work

- src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
The `1.35.1` tag was created before #1480 was merged, and the PR was merged with a squash merge, so the tagged commit is not currently visible from the `master` branch.
Once this PR is merged with a regular merge commit (and NOT a squash), this will get the tagged commit back as part of the `master` branch.
> Fix problem with tag not being visible on master branch

- .github/workflows/ci.yml
- .github/workflows/release.yml
- src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
- src/ServicePulse.Install.CustomActions/CustomAction.cs
- src/ServicePulse.Install.CustomActions/ServicePulse.Install.CustomActions.csproj
- src/ServicePulse.sln
- src/Setup/Setup.csproj
This PR includes the following: 
- Wix Toolset updated to v4, which no longer requires .NET Framework 3.5 and works with SDK projects without workarounds
- Changes to how the Windows Installer gets built, matching how it is handled in ServiceControl
- Removed an unneeded package reference
- Tweaks to workflow files
> Repo updates

- src/ServicePulse.Host/angular/app/js/.eslintrc.js
- src/ServicePulse.Host/angular/app/js/views/endpoints/endpoints.controller.js
- src/ServicePulse.Host/angular/app/js/views/endpoints/endpoints.html
This adds a dropdown to the filter section which allows the user to show only the endpoints' logical names instead of always physical.
It also includes some summary information about how many endpoints are beating and how many used to be beating.
Configuration still allows the user to disable individual instances.
Documentation PR: https://github.com/Particular/docs.particular.net/pull/6069
> Allow displaying logical endpoint

- src/ServicePulse.Host/vue/src/assets/navbar.css
Solves https://github.com/Particular/ServicePulse/issues/1503
When browser width less than 992px the menu jumps outside the navbar
> Fix navbar alignment when screen less than 992px

- .github/workflows/release.yml
- src/Setup/Setup.csproj
This aligns the Setup project with the approach used in ServiceControl, where the required value is set in the project file, so it will always be available regardless of how the project is built.
> Use RepoRootDir property instead of SolutionDir

- src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
- Original Issue: https://github.com/Particular/ServicePulse/issues/1526
- Internal issue: https://github.com/Particular/PlatformBugs/issues/1224
This PR disables the "Edit & Retry" button on a failed message that has already been edited and retried.
> Disable "Edit & Retry" on an already edited and retried message 

- src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
This PR fixes [Connection test fails if the url does not end with a slash  #1469](https://github.com/Particular/ServicePulse/issues/1469)
> add trailing slash to monitoring url

- .vscode/launch.json
- src/ServicePulse.Host/.vscode/launch.json
- src/ServicePulse.Host/vue/package.json
Adding vscode configurations for interactive debugging.
Debugging configurations are available when vscode is opened from any of the following locations:
- the repo root
- src/ServicePulse.Host
- src/ServicePulse.Host/vue
> Enabling vscode interactive debugger from multiple folders

- src/ServicePulse.Host/vue/vite.config.js
While using the browser DevTools to inspect CSS, it is only possible to know what file a style is coming from if source maps files are enabled for development.
> Enable css sourcemaps

- src/ServicePulse.Host/vue/src/assets/main.css
- src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
Simplify the HTML used for the layout of the EndpointList component and its related CSS classes. 
Instead of using Bootstrap and creating other classes to overwrite some unwanted styles from Bootstrap, let's use "new/clean" classes that do the same work but with less code.
> Simplify EndpointList component HTML and CSS 

- src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
- src/ServicePulse.Host/vue/src/composables/serviceMonitoringEndpoints.js
- src/ServicePulse.Host/vue/src/stores/FailedMessageStore.js
- src/ServicePulse.Host/vue/src/stores/MonitoringStore.js
Add Pinia store to the endpoint details page in order to retrieve the following 
- Endpoint details
- Failed messages count 
The PR also has added the option to retrieve the disconnected endpoint count
> Endpoint details pinia store

- src/ServicePulse.Host/vue/src/components/failedmessages/EditMessageHeader.vue
When the [edit and retry](https://docs.particular.net/servicepulse/intro-editing-messages) functionality is enabled, clicking the button to delete or reset a header navigates to the dashboard. This prevents the user from completing the retry operation.
The actions are anchor tags which had an `href="#"` attribute. With the href in place the browser navigates away from the modal. This can also be solved with `.prevent` event modifiers but the href is not needed.
> Fix header change actions

- src/ServicePulse.Host/vue/src/components/EventItemShort.vue
- src/ServicePulse.Host/vue/src/components/LicenseExpired.vue
- src/ServicePulse.Host/vue/src/components/PageFooter.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/configuration/EndpointConnection.vue
- src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications.vue
- src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
- src/ServicePulse.Host/vue/src/components/configuration/PlatformLicense.vue
- src/ServicePulse.Host/vue/src/components/configuration/RetryRedirects.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/PendingRetries.vue
- src/ServicePulse.Host/vue/src/composables/serviceLicense.js
- src/ServicePulse.Host/vue/src/composables/serviceMessageGroup.js
- src/ServicePulse.Host/vue/src/composables/serviceRedirects.js
- src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js
- src/ServicePulse.Host/vue/src/views/ConfigurationView.vue
- src/ServicePulse.Host/vue/src/views/DashboardView.vue
- src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue
This is quite a few files, but is just removing the `.js` from the imports, so that once we rename the files to `.ts` we don't need to revisit these imports.
> Removing .js from imports

- src/ServicePulse.Host/vue/src/components/BusyIndicator.vue
- src/ServicePulse.Host/vue/src/components/ConfirmDialog.vue
- src/ServicePulse.Host/vue/src/components/DashboardItem.vue
- src/ServicePulse.Host/vue/src/components/DataView.vue
- src/ServicePulse.Host/vue/src/components/DataViewPageModel.ts
- src/ServicePulse.Host/vue/src/components/EventItemShort.vue
- src/ServicePulse.Host/vue/src/components/EventLogItem.vue
- src/ServicePulse.Host/vue/src/components/ExclamationMark.vue
- src/ServicePulse.Host/vue/src/components/ItemsPerPage.vue
- src/ServicePulse.Host/vue/src/components/LicenseExpired.vue
- src/ServicePulse.Host/vue/src/components/NoData.vue
- src/ServicePulse.Host/vue/src/components/PageFooter.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/PaginationStrip.vue
- src/ServicePulse.Host/vue/src/components/ServiceControlNotAvailable.vue
- src/ServicePulse.Host/vue/src/components/ToastPopup.vue
- src/ServicePulse.Host/vue/src/components/WarningLevel.ts
- src/ServicePulse.Host/vue/src/components/configuration/PlatformLicense.vue
- src/ServicePulse.Host/vue/src/components/configuration/convertToWarningLevel.ts
- src/ServicePulse.Host/vue/src/composables/LicenseStatus.ts
- src/ServicePulse.Host/vue/src/composables/serviceLicense.ts
- src/ServicePulse.Host/vue/src/composables/toast.ts
- src/ServicePulse.Host/vue/src/resources/EventLogItem.ts
- src/ServicePulse.Host/vue/src/views/ConfigurationView.vue
- src/ServicePulse.Host/vue/src/views/DashboardView.vue
- src/ServicePulse.Host/vue/src/views/EventsView.vue
I am not 100% happy with the generic `DataView` implementation.
I may raise an issue in vue to determine if there is a nicer way of doing that.
Apart from that, all the other conversions are straightforward.
> More vue converted to TypeScript

- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/FlowDiagram.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
- src/ServicePulse.Host/vue/vite.config.ts
Fixed applied after smoke testing 1.38.0
- Configuration tab disappears when license warning is rendered
- Content Security Policy is too restrictive
- Failed Message titles are not bolded
> Fixed issues found in 1.38.0 smoke test

- .github/workflows/ci.yml
This PR is removing storybook from the CI in order to not hold up other PRs
There will be another PR dedicated to storybook addressing the following:
- Introduction of Pinia 
- Stories will be reviewed/re-wired for all the applicable components
- Upgrad storybook the the latest version
> Temporarily remove storybook from CI

- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
- src/ServicePulse.Host/angular/.npmrc
- src/ServicePulse.Host/build.ps1
- src/run-dev.cmd
Adds the `NODE_OPTIONS = "--openssl-legacy-provider"` to the `.npmrc` file in the root directory for the angular app. This allows any `npm` commands run in the angular directory to use the `NODE_OPTIONS` environment variable, which allows compatibility with Node.js versions 17 and above.
The node-version in the ci.yml and release.yml have been pinned to version 21.6.x for now.  This version will need to be manually updated in future releases, as it is not picked up by dependabot.
> Add NODE_OPTIONS environment variable to build.ps1

- src/ServicePulse.Host/vue/src/main.ts
- src/ServicePulse.Host/vue/src/mount.ts
- src/ServicePulse.Host/vue/src/router/index.ts
Extracting the mounting of the app into a function for reuse in acceptance tests. This allows to
- Pass a fresh instance of the router per each test running in parallel without interfering with each other
- Use a real router instead of a mocked one.
> Extracting mounting of the app into a function

- src/ServicePulse.Host/vue/vitest.config.ts
The virtual screen (JSDOM) is being reused between tests runs, making rendered components from other tests to stick. This PR fixes the problem.
> Fix: clear virtual dom between component tests runs

- src/ServicePulse.Host/vue/src/components/EventItemShort.vue
- src/ServicePulse.Host/vue/src/components/EventLogItem.vue
- src/ServicePulse.Host/vue/src/components/LicenseExpired.vue
- src/ServicePulse.Host/vue/src/components/PageFooter.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/ServiceControlNotAvailable.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/FlowDiagram.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
- src/ServicePulse.Host/vue/src/router/config.ts
- src/ServicePulse.Host/vue/src/router/index.ts
- src/ServicePulse.Host/vue/src/router/routeLinks.ts
- src/ServicePulse.Host/vue/src/router/vue-router.d.ts
- src/ServicePulse.Host/vue/src/views/ConfigurationView.vue
- src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue
As part of the work I am doing for the throughput reporting, I need to add a new top nav link, and I noticed all our links are hard coded and not centralised.
So this is just a cleanup for better linking within the app.
So from a consumer perspective, you know take in `routerLinks`, and then you reference a link, eg:
```
<RouterLink :to="routeLinks.dashboard">
```
I have updated all hardcoded links to use this new way, with the exception of https://github.com/Particular/ServicePulse/blob/843554f03ee27cda1a5ae32140b53c4a5149a763/src/ServicePulse.Host/vue/src/composables/serviceLicense.ts#L10-L17 which should use templates!
> Added typed links

- src/ServicePulse.Host/vue/src/components/SortableColumn.vue
- src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
- src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
- src/ServicePulse.Host/vue/src/components/monitoring/MonitoringGroupBy.vue
- src/ServicePulse.Host/vue/src/components/monitoring/endpoint.css
- src/ServicePulse.Host/vue/src/stores/MonitoringStore.js
- src/ServicePulse.Host/vue/src/views/MonitoringView.vue
Adds sorting to the endpoint name column when the endpoint list is grouped by segments.  This also correctly displays the short name of the endpoint when the list is grouped.
> Endpoint name group sorting

- src/ServicePulse.Host/vue/src/components/PaginationStrip.vue
This can happen if the number of items per page changes. i.e. If you have 2 pages of 25 items each, and you are on page 2, and then change the number of items per page to 75.
> Handle case where current page exceeds total page count

- src/ServicePulse.Host/vue/src/composables/formatter.ts
Instead of 0, it should be 0 ms
Before:
After:
> Add default time unit

- src/ServicePulse.Host/vue/src/composables/formatter.ts
Before (English): 
After (en-AU):
After (de-AT):
After (nl):
> Format large numbers with locale

- src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
- src/ServicePulse.Host/vue/src/components/monitoring/endpoint.css
- src/ServicePulse.Host/vue/src/router/routeLinks.ts
display connectedcount/total rather than just connectedcount and separate the display from the endpoint link
> display connectedcount/total rather than just connectedcount

- src/ServicePulse.Host/vue/src/stores/MonitoringStore.ts
This is used on the endpoint details screen which has it's own store. Nothing ever accesses or updates this value.
> Remove unused ref

- src/ServicePulse.Host/vue/src/components/SortableColumn.vue
> By saying the prop is required, you expect the user to always provide a value, so making it have a default value defeats the purpose of the prop being required.
According to:
- https://github.com/vuejs/vue/issues/7720#issuecomment-369172012
> Fixes [Vue warn]: Missing required prop: "defaultAscending"

- src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
The cursor was not a hand when hovering the red circle with the number of failed messages
> Fixing endpoint details header icon

- src/ServicePulse.Host/vue/src/views/DashboardView.vue
- src/ServicePulse.Host/vue/src/views/EventsView.vue
- src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue
I noticed a lack of consistent headers, so this PR ensures all top-level pages are consistent.
I followed the "Configuration" page as the template to follow.
Dashboard
Events
Failed Messages
Removed "Dashboard" title, given this is the main page, I don't think we need the "Dashboard" title
Events page
Failing Messages
> Consistent header per page

- src/ServicePulse.Host/vue/src/assets/header-menu-item.css
- src/ServicePulse.Host/vue/src/components/EventLogItem.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/customchecks/CustomCheckView.vue
- src/ServicePulse.Host/vue/src/components/customchecks/CustomChecksDashboardItem.vue
- src/ServicePulse.Host/vue/src/components/customchecks/CustomChecksMenuItem.vue
- src/ServicePulse.Host/vue/src/composables/autoRefresh.ts
- src/ServicePulse.Host/vue/src/composables/serviceServiceControl.ts
- src/ServicePulse.Host/vue/src/stores/CustomChecksStore.ts
- src/ServicePulse.Host/vue/src/views/CustomChecksView.vue
- src/ServicePulse.Host/vue/src/views/DashboardView.vue
Moves the custom checks data management to a pinia store.
> Custom checks with Pinia store

- src/ServicePulse.Host/vue/src/assets/header-menu-item.css
- src/ServicePulse.Host/vue/src/components/FeedbackButton.vue
- src/ServicePulse.Host/vue/src/components/PageHeader.vue
- src/ServicePulse.Host/vue/src/components/configuration/ConfigurationMenuItem.vue
- src/ServicePulse.Host/vue/src/components/customchecks/CustomChecksMenuItem.vue
- src/ServicePulse.Host/vue/src/components/dashboard/DashboardMenuItem.vue
- src/ServicePulse.Host/vue/src/components/events/EventsMenuItem.vue
- src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessagesMenuItem.vue
- src/ServicePulse.Host/vue/src/components/heartbeats/HeartbeatsMenuItem.vue
- src/ServicePulse.Host/vue/src/components/monitoring/MonitoringMenuItem.vue
This PR moves all of the nav item elements into their own components and then renders them based on a data-driven list.
It also shifts the CSS for active items to use the built-in vue classes
> Refactor page header component

- src/ServicePulse.Host/vue/src/components/configuration/EndpointConnection.vue
ServiceControl returns more data, including `SagaAudit` and `MessageAudit` settings, which were not displayed in ServicePulse. Second, the top-level properties should be `PascalCase`, too (it's not a bug; the connector plugin works with `camelCase` properties as well, but for consistency, it's preferable).
> Add missing SagaAudit and MessageAudit sections and capitalize properties as expected by the connector plugin

- src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
- src/ServicePulse.Host/vue/src/composables/servicePulseFetch.ts
- src/ServicePulse.Host/vue/src/composables/serviceServiceControlUrls.ts
This PR adds `Particular-ServicePulse-Version` header to all ServiceControl instance calls.
ServiceControl will use this information as part of https://github.com/Particular/ServiceControl/pull/3965.
The plan is to send this data as part of the report generation that customer produce.
> Adding ServicePulse version to all requests to ServiceControl instances

- src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
Fixes https://github.com/Particular/ServicePulse/issues/1828
- https://github.com/Particular/ServicePulse/issues/1828
the message body/header details were being set to blank and then back to their previous values on each refresh, since failedMessage.value was being set before retrieving all of the details. This change ensures that failedMessage.value only gets set with the final, complete, message details
> fix message view flickering and resetting scroll position

- README.md
Now that the ServicePulse `master` branch no longer uses AngularJS, there is no need to set up the Nginx proxy and run an AngularJS development server. This PR updates the README to remove those requirements, applies minor wording changes, and fixes some typos.
> Remove AngularJS and Nginx from the README

- src/ServicePulse.Host/vue/src/composables/serviceFailedMessage.ts
The ServiceControl `master` branch switched from `Newtonsoft.Json` to `System.Text.Json`, which is less permissive.
When ServicePulse retries an edited failed message, it posts to ServiceControl the edited body and edited headers alongside a bunch of unrelated header properties (that ServicePulse uses to pilot the edit dialog user interface). `Newtonsoft.Json` happily accepted the incoming headers with additional properties to an `IEnumerable<KeyValuePair<string, string>>`, discarding the additional properties. The most recent ServiceControl version expects a `Dictionary<string, string>` and `System.Text.Json` is not so flexible and throws a deserialization exception.
This PR changes how ServicePulse posts the header by only posting header keys and values without the additional …
> When editing a failed message copy from edited headers only keys and values

- src/ServicePulse.Host/vue/src/composables/autoRefresh.ts
This is an attempt to prevent flaky application tests. Sometimes, the window object could have been disposed from the test environment by the time window.clearTimeout is invoked. It may be the case that this change is not enough, and invoking the clearTimeout function directly instead of a window.clearTimeout also fails.
> Fix to prevent flaky tests

- src/Frontend/src/composables/serviceNotifications.ts
- src/Frontend/src/composables/serviceRedirects.ts
HTTP/2 doesn't support the reason phrase when returning errors in an HTTP response. In ServiceControl, we then stopped using it and, for now, moved to a custom `X-Particular-Reason` header ([see, for example, this controller](https://github.com/Particular/ServiceControl/blob/da452ea82a2cf6aca420d73029c7861cc009c764/src/ServiceControl/MessageRedirects/Api/MessageRedirectsController.cs#L55-L58)). A proper solution is more complex and out of scope for now. 
This PR updates ServicePulse to use the new header.
> Use the X-Particular-Reason header to get the response StatusText from ServiceControl versions later than 5.1

- src/Frontend/package.json
- src/ServicePulse.Host/build.ps1
Remove msw dir setting in package.json file in order to prevent the generation of mockServiceWorker.js when restoring dependencies
> Ensure mockServiceWorker.js is not included in the build

- src/Frontend/src/components/configuration/RetryRedirectEdit.vue
When using retry redirects, ServicePulse warns when the "To physical address" endpoint is unknown. The error message talks about audited messages and is misleading. ServicePulse only queries for queues where a message failed. This PR fixes the error message.
> Fix the retry redirect error message to not mention audited messages

- README.md
scConfig is a constant that was used in angular code, also the path of the `ServicePulse.Host/vue/public/app/js/app.constants.js` was incorrect
> Removing more AngularJs references

- src/Frontend/test/preconditions/serviceControlWithMonitoring.ts
Since the acceptance tests setup run the whole application for every single test, every call that can potentially be made to Service Control requires to be mocked. This PR adds default handlers for the /licensing paths (/test, /endpoints, /available) 
Since this commit [1c1640f](https://github.com/Particular/ServicePulse/pull/1746/commits/1c1640f8a20e4c71ef38bc40915e65992742970e) is now initializing the report store from the menuItem, it triggers the Throughput client, which in turn calls /licenses/tests in a timer. This requires having the report paths at least with a default handler. These handlers can be overwritten when writing specific test cases.
> Report build fix: Adding default mocked respones for /licensing/* API calls

- src/Frontend/src/composables/serviceServiceControl.ts
- src/Frontend/src/stores/MonitoringStore.ts
- src/Frontend/src/views/MonitoringView.vue
This removes a call to get monitored-endpoints from `useServiceControlMonitoringStats()`, since the results are never used there is no reason to set an interval to call this function every 5 seconds on app start up.
Also, refactored the monitoring store, removing the `initializeStore()` function
In the master branch you can see that even when the history period is set to 10 minutes (so the refresh should be 10 seconds) the fetch is happening 3 times right after the page is reloaded. And there is also a fetch to `history=1`, which was being done on a 5 second interval by the `useServiceControlMonitoringStats()` on app startup.
After removing the fetch calls from the from `useServiceControlMonitoringStats()` the 3 initial fetch calls are removed and the fetch call to `history=1` is also not …
> Remove unnecessary monitoring-endpoint calls

- src/Frontend/src/components/failedmessages/EditRetryDialog.vue
- src/Frontend/test/driver.ts
- src/Frontend/test/drivers/vitest/driver.ts
- src/Frontend/test/mock-endpoint.ts
- src/Frontend/test/mocks/browser.ts
- src/Frontend/test/preconditions/hasNoErrors.ts
- src/Frontend/test/preconditions/index.ts
- src/Frontend/test/preconditions/recoverability.ts
- src/Frontend/test/preconditions/serviceControlWithMonitoring.ts
- src/Frontend/test/specs/failedmessages/actions/openEditAndRetryEditor.ts
- src/Frontend/test/specs/failedmessages/edit-and-retry.spec.ts
- src/Frontend/test/specs/failedmessages/questions/getEditAndRetryEditor.ts
- src/Frontend/test/utils.ts
Edit and Retry Content type check allows more text based payloads by allowing all text based content types which start with `text/` but also all `application/*+json` and `application/*+xml` payloads
> Edit and Retry Content type check allows more text based payloads

- src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
Also updated some dependencies
This fixes error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w [D:\a\ServicePulse\ServicePulse\src\ServicePulse.sln]
This is just a dependency of the tests, hence no need to release.
> Fixing issue with System.Text.Json high severity vulnerability in our tests

- src/Frontend/src/stores/ThroughputStore.ts
The logic should be:
1. if it is a broker, we return true if the broker connection is unsuccessful
2. if the Audit test connection is false, we return true symbolizing that we have errors;
3. if monitoring is enabled, we return whatever the value of the test connection is for monitoring;
4. by default we return no errors
> Fix incorrect logic to display error icon for Usage setup 

- .github/dependabot.yml
We adding grouping for npm packages, so that it reduces the amount of PRs to deal with.
In this PR we are bundling all patch fixes in a single PR for all packages.
> grouping patch updates for npm

- src/Frontend/src/components/AutoRefreshDataView.vue
- src/Frontend/src/components/DataView.vue
- src/Frontend/src/components/EventItemShort.vue
- src/Frontend/src/components/LicenseNotExpired.vue
- src/Frontend/src/components/OnOffSwitch.vue
- src/Frontend/src/components/SortableColumn.vue
- src/Frontend/src/components/TimeSince.vue
- src/Frontend/src/components/configuration/HealthCheckNotifications.vue
- src/Frontend/src/components/heartbeats/HeartbeatConfiguration.vue
- src/Frontend/src/views/EventsView.vue
- src/Frontend/src/views/HeartbeatsView.vue
Pulls independent component related changes out of #2019
> A few component changes

- src/Frontend/test/specs/monitoring/sorting-endpoints.spec.ts
fixes #2057 
The scenario named "**EXAMPLE: Sort up and down arrow images should alternate visibility only on the column where the title was clicked"** times out a lot of times
> Flaky test test fix - test/specs/monitoring/sorting-endpoints.spec.ts

- Container-README.md
- src/ServicePulse/ConstantsFile.cs
- src/ServicePulse/Program.cs
- src/ServicePulse/ReverseProxy.cs
- src/ServicePulse/Settings.cs
This PR adds the following features to the container host:
- The reverse proxy can now be disabled by setting the `ENABLE_REVERSE_PROXY` environment variable to `false`.
- The reverse proxy no longer assumes the structure of the URLs passed via the `SERVICECONTROL_URL` and `MONITORING_URL` settings will use the value as passed in.
NOTE: Regardless of the two changes above, the `SERVICECONTROL_URL` value is still inspected to see if it ends with `/api/` and will append that as needed to ensure a valid URL.
Closes #2076
> Proxy improvements

- .github/dependabot.yml
- src/Frontend/test/specs/monitoring/sorting-endpoints.spec.ts
I have decided to skip a random failing test for now, see https://github.com/Particular/ServicePulse/actions/runs/11296984618/job/31422942849?pr=2104#step:7:780
I have also updated the location of the docker file that dependbot looks for.
> A few small fixes

- src/Frontend/src/components/failedmessages/FailedMessages.vue
Resolves:
- https://github.com/Particular/ServicePulse/issues/2178
CSV export failed to generate a correct CSV as the value can contains `\n`, `,` or `"`.
This change will:
- Put the value in double quotes if `\n`, `,` or `"` characters are in the "cell" value
- Escape `"` characters to `""` which seems to be the most common used method to escape double quote characters
> Fix CSV export with values containing `\n`, `,` or `"`

- .github/workflows/push-container-images.yml
- .github/workflows/release.yml
- src/ServicePulse/Dockerfile
Using native action to login to ghcr.io.
Replaced multiple tagging commands with a single one Using build-push-action instead of script.
This adds the provenance by default, see https://docs.docker.com/build/ci/github-actions/attestations/#default-provenance .
This gives the image a better score in DockerHub Scout health score.
This is the same changes as https://github.com/Particular/ServiceControl.Connector.MassTransit/pull/182.
> Improving provenance of image

- src/Frontend/test/preconditions/licensing.ts
- src/Frontend/test/specs/configuration/viewing-license.spec.ts
Due to the time component of the mock date, the number of days left for expiration was not consistently returning the correct days left due to timezone off sets. This resulted in some of the licensing tests failing randomly . Eg: https://github.com/Particular/ServicePulse/actions/runs/13488622751/job/37683212711?pr=2259#step:7:3254
This PR resets  the time component to zero to remove time zone flakiness in tests
> set the time component to zero to remove time zone flakiness

- src/Frontend/src/components/configuration/PlatformLicense.vue
- src/Frontend/src/composables/serviceLicense.ts
- src/Frontend/src/resources/EndpointThroughputSummary.ts
- src/Frontend/src/resources/LicenseInfo.ts
- src/Frontend/src/views/throughputreport/endpoints/DetectedListView.spec.ts
- src/Frontend/src/views/throughputreport/endpoints/DetectedListView.vue
- src/Frontend/src/views/throughputreport/endpoints/useHiddenFeature.ts
This is to support future license models based on monthly usage.
This PR is backward-compatible, but in order to test it, you need https://github.com/Particular/ServiceControl/pull/4863
> Add displaying of usage per month

- src/Frontend/src/views/throughputreport/setup/ConnectionSetupView.vue
This PR updates the conditions on the throughput connection setup page to match the conditions that control the two lower sections.
This change avoids displaying the intro paragraph when neither of the two lower sections will be displayed, which happens when a broker transport has no settings to configure.
The RabbitMQ transport will no longer have separately configurable settings once https://github.com/Particular/ServiceControl/pull/4755 ships as part of a ServiceControl release.
> Update condition for when broker transport has no throughput connection settings

- src/Frontend/package-lock.json
- src/Frontend/src/components/EventLogItem.vue
- src/Frontend/src/components/failedmessages/MessageList.vue
- src/Frontend/src/components/failedmessages/MessageRedirectForBackwardsCompatibility.vue
- src/Frontend/src/components/messages/FlowDiagram.vue
- src/Frontend/src/components/messages/MessageView.vue
- src/Frontend/src/composables/serviceServiceControlUrls.ts
- src/Frontend/src/router/config.ts
- src/Frontend/src/router/routeLinks.ts
- src/Frontend/src/views/FailedMessagesView.vue
This is in preparation for a new "All messages" area.
The goal is to share the same view for successful and failed messages.
This is a first step in this direction.
> Moved message display to be under /messages

- src/Frontend/src/App.vue
- src/Frontend/src/components/BackendChecksNotifications.vue
- src/Frontend/src/components/LicenseNotifications.vue
- src/Frontend/src/components/failedmessages/EditRetryDialog.vue
- src/Frontend/src/components/messages/BodyView.vue
- src/Frontend/src/components/messages/FlowDiagram.vue
- src/Frontend/src/components/messages/HeadersView.vue
- src/Frontend/src/components/messages/MessageView.vue
- src/Frontend/src/components/messages/StacktraceView.vue
- src/Frontend/src/mount.ts
This PR refactors the tabs views for the message to be their components
> Refactor message  tabs views into separate components

- src/Frontend/src/components/messages/MessageView.vue
- src/Frontend/test/specs/failedmessages/edit-and-retry.spec.ts
This should fix the flaky test:
> Update test to use new url

- src/Frontend/package-lock.json
- src/Frontend/package.json
- src/Frontend/src/components/CodeEditor.vue
- src/Frontend/src/components/CopyToClipboard.vue
- src/Frontend/src/components/codeEditorTypes.ts
- src/Frontend/src/components/configuration/EndpointConnection.vue
- src/Frontend/src/components/failedmessages/EditRetryDialog.vue
- src/Frontend/src/components/failedmessages/MessageRedirectForBackwardsCompatibility.vue
- src/Frontend/src/components/messages/BodyView.vue
- src/Frontend/src/components/messages/MessageView.vue
- src/Frontend/src/components/messages/StacktraceView.vue
- src/Frontend/src/composables/contentTypeParser.ts
- src/Frontend/src/mount.ts
- src/Frontend/src/resources/FailedMessage.ts
- src/Frontend/src/views/throughputreport/setup/ConfigurationCode.vue
- src/Frontend/src/vue-highlight-code.d.ts
- src/Frontend/test/specs/failedmessages/edit-and-retry.spec.ts
- src/Frontend/test/specs/failedmessages/questions/getEditAndRetryEditor.ts
This PR adds CodeMirror as the code editor and syntax highlighter.
I changed the stack trace to use the editor. At the moment, the syntax highlighter for the stack trace uses the "PowerShell" language, which highlights it slightly but not super nicely. We can write a [custom language](https://codemirror.net/examples/lang-package/) for it later.
Also added syntax highlighting to the message body in both view and editing mode.
For editing mode, we can add lint so that it helps the user avoid syntax mistakes. See https://codemirror.net/examples/lint/
The editor has:
- code folding
- copy to clipboard
- line numbers
> Adding CodeMirror editor for code highlighting and editing

- src/Frontend/src/components/CopyToClipboard.vue
- src/Frontend/src/components/messages/HeadersView.vue
This PR adds a copy icon next to each message header, enabling the copy of the header value to the clipboard.
> Copy feature in message headers in message view

- src/Frontend/src/components/failedmessages/DeletedMessageGroups.vue
- src/Frontend/src/components/failedmessages/FailedMessageGroups.vue
- src/Frontend/src/components/failedmessages/FailedMessages.vue
- src/Frontend/src/components/failedmessages/PendingRetries.vue
As per https://vuejs.org/guide/essentials/template-refs
I noticed this as part of the current work we are doing.
> Change to useTemplateRef for refs

- src/Frontend/src/components/CodeEditor.vue
This fixes issue with overflow in dialogs
> Turn on wordwrap on code editor

- src/Frontend/src/components/messages/HeadersView.vue
Adds a search input in the message header view that filters the header key based on that search term
> Add search input to  message headers view

- src/Frontend/src/components/CopyToClipboard.vue
Small improvement, it seems using a watcher is a better way to clearing previous timeouts
> Clears previous timeout when copying

- src/Frontend/src/components/TextEllipses.vue
This is to deal with large text display.
The component will automatically add a tooltip based on whether the text overflows.
The ellipses can be added to either side of the text.
> Adding TextEllipses component

- src/Frontend/src/components/messages2/SequenceDiagram.vue
- src/Frontend/src/components/messages2/SequenceDiagram/EndpointsComponent.vue
- src/Frontend/src/components/messages2/SequenceDiagram/HandlerTooltip.vue
- src/Frontend/src/components/messages2/SequenceDiagram/HandlersComponent.vue
- src/Frontend/src/components/messages2/SequenceDiagram/RoutesComponent.vue
- src/Frontend/src/components/messages2/SequenceDiagram/tooltipOverlay.ts
- src/Frontend/src/resources/SequenceDiagram/Handler.ts
- src/Frontend/src/resources/SequenceDiagram/SequenceModel.ts
- src/Frontend/src/stores/SequenceDiagramStore.ts
Implement message selection/navigation as per ServiceInsight functionality, highlighting current message
also keep endpoint names visible during y-scrolling
> Sequence Diagram message selection

- src/Frontend/src/components/FilterInput.vue
- src/Frontend/src/components/audit/AuditList.vue
- src/Frontend/src/components/audit/FiltersPanel.vue
- change the double-watch pattern for locally synced models to instead use a writeable calculated
- fix styling of audit list to match other areas in SP
- fix styling of filterinput to be in rem/em where it makes sense
> Make calculated models clearer

- src/Frontend/src/components/messages2/HeadersView.vue
alternative to https://github.com/Particular/ServicePulse/pull/2314
> size header list according to contents and eliminate size jump on hover

- src/Frontend/src/components/messages2/FlowDiagram/FlowDiagram.vue
- src/Frontend/src/components/messages2/FlowDiagram/useLayout.ts
> Remove show/hide address

- src/Frontend/src/components/CodeEditor.vue
- src/Frontend/src/components/messages2/BodyView.vue
- src/Frontend/src/components/messages2/FlowDiagram/FlowDiagram.vue
- src/Frontend/src/components/messages2/HeadersView.vue
- src/Frontend/src/components/messages2/SagaDiagram.vue
- src/Frontend/src/components/messages2/SequenceDiagram.vue
@cquirosj this is the aligning the look and feel for all the tabs, that we discussed.
I also fixed the icon and style of the button in saga diagram.
> Align look and feel for all tabs

- src/Frontend/src/components/messages2/SagaDiagram/SagaDiagramParser.ts
- src/Frontend/src/components/messages2/SagaDiagram/SagaOutgoingTimeoutMessage.vue
- src/Frontend/src/components/messages2/SagaDiagram/SagaUpdateNode.vue
- src/Frontend/src/stores/SagaDiagramStore.ts
Given a saga with an outgoing timeout message that has been processed
When the user clicks on the timeout link
Then the page scrolls to the corresponding incoming timeout message
And the incoming timeout message is highlighted with a blinking animation
Given a saga with an outgoing timeout message that has not been processed
When the user views the saga diagram
Then the timeout message is displayed as non-clickable text
Given a saga with multiple outgoing timeout messages that have been processed
When the user clicks on one timeout message and then another
Then only the most recently clicked timeout message is highlighted
And the previously highlighted timeout message is no longer highlighted
> Saga diagram: Navigate to timeout message

- src/Frontend/src/components/FilterInput.vue
- src/Frontend/src/components/audit/FiltersPanel.vue
I have to use a font awesome image for the wildcard character becasue by default it prints quite small `*`. So not really visible!
> Tooltip to use wildcards

- src/Frontend/src/components/CodeEditor.vue
- src/Frontend/src/components/failedmessages/EditRetryDialog2.vue
- src/Frontend/src/components/messages2/EditAndRetryButton.vue
- src/Frontend/src/components/messages2/FlowDiagram/FlowDiagram.vue
- src/Frontend/src/components/messages2/RetryMessageButton.vue
- src/Frontend/src/stores/MessageStore.ts
- src/Frontend/src/stores/SequenceDiagramStore.ts
The edit and retry dialog was suppose to show a "reset body" back to the original button.
But unfortunately the logic had a few bugs which cuased the button to not always be shown.
This PR fixes that issue as well as brings the button to the top of the dialog to be more inline with current design in other areas.
> Fix reset original body

- src/Frontend/package-lock.json
- src/Frontend/package.json
- src/Frontend/src/components/RefreshConfig.vue
- src/Frontend/src/components/audit/AuditList.vue
- src/Frontend/src/stores/AuditStore.ts
Added throttle so not too many calls to refresh happen in succession. 
Updated the UI to simplify auto refresh, it is now just a button and a dropdown.
> Removed auto-refresh from store

- src/Frontend/src/components/audit/AuditList.vue
- src/Frontend/src/components/audit/FiltersPanel.vue
replace wildcard tooltip with static text and  replace the instructions text to get a cleaner and tighter look.
Old way of using a tooltip
New way of using a static text
> replace wildcard tooltip with static text, replace the instructions text

- src/Frontend/src/components/messages2/MessageView.vue
Hide the saga tab  if the endpoint is not part of a saga
> Hide the saga tab  if the endpoint is not part of a saga

- src/Frontend/src/components/audit/AuditList.vue
- src/Frontend/src/components/audit/FiltersPanel.vue
Brings the note style inline with already established style ibn other parts of the UI.
> Align note style with already established styles

- src/Frontend/src/components/messages2/HeadersView.vue
This is an alternative for https://github.com/Particular/ServicePulse/pull/2372
This option is more inline with the existing sticky filters in message list screen.
With sticky filters:
Existing sticky filter in all messages list
> Sticky filter for headers

- src/Frontend/src/composables/serviceServiceControl.ts
- src/Frontend/src/views/AuditView.vue
Ensure we check connection first
> Update minimum versions

- src/Frontend/src/components/audit/AuditList.vue
add loading spinner in all messages list page
> add loading spinner in all messages list page

- src/Frontend/src/components/MaximizableCodeEditor.vue
- src/Frontend/src/components/messages2/DiffViewer.vue
- src/Frontend/src/components/messages2/SagaDiagram.spec.ts
- src/Frontend/src/components/messages2/SagaDiagram/MessageDataBox.vue
- src/Frontend/src/components/messages2/SagaDiagram/SagaDiagramParser.ts
- src/Frontend/src/components/messages2/SagaDiagram/SagaOutgoingMessage.vue
- src/Frontend/src/components/messages2/SagaDiagram/SagaOutgoingTimeoutMessage.vue
- src/Frontend/src/components/messages2/SagaDiagram/SagaUpdateNode.vue
- src/Frontend/src/stores/DataContainer.ts
- src/Frontend/src/stores/MessageStore.ts
- src/Frontend/src/stores/SagaDiagramStore.ts
> Display saga messages body using CodeEditor

- src/Frontend/src/components/messages2/FlowDiagram/FlowDiagram.vue
fix the tippy text on the message node of flow diagram
> fix the tippy text on the message node of flow diagram

- src/Frontend/src/components/messages2/StacktraceFormatter.vue
- src/Frontend/src/components/messages2/StacktraceView.vue
Based on https://github.com/elmahio/netStack.js/tree/main
This changes the style of the stacktracer visualiser to utilise the library that is used in https://elmah.io/tools/stack-trace-formatter/
Initially when I first used the CodeEditor to render stacktraces the best syntax highlighter i found was the one for Powershell. But even that was not ideal.
This is a custom highlighter utilising the https://github.com/elmahio/netStack.js to render the c# stacktraces.
The only difference is that the code has been turned into a vue typed component.
> Adding new stacktrace visualiser

- src/Frontend/src/components/messages2/EditAndRetryButton.vue
Fixes https://github.com/Particular/ServicePulse/issues/2424
> Fixes double retry when using edit and retry

- src/Frontend/src/components/messages/ExportMessageButton.vue
The export message function is generic and is also applied in the message view. Therefore, failedMessage.txt is not exactly an appropriate name for the text file
> Rename text file to something more generic

- src/Frontend/package-lock.json
- src/Frontend/package.json
- src/Frontend/src/assets/main.css
- src/Frontend/src/components/OrderBy.vue
- src/Frontend/src/components/failedmessages/FailedMessageGroups.vue
- src/Frontend/src/components/failedmessages/FailedMessages.vue
- src/Frontend/src/components/failedmessages/MessageList.vue
- src/Frontend/src/components/failedmessages/PendingRetries.vue
- src/Frontend/vite.config.ts
I just updated the bootstrap-icons package to the latest version, but then I thought to search the code base and see how easy would be to remove that dependency.
So in this PR I have replaced the bootstrap-icons usage with the equivalent from font-awesome.
For reference here are the icons before - https://icons.getbootstrap.com/?q=sort
And after https://fontawesome.com/v4/icons/
> Remove bootstrap-icons dependency and update icon references to FontAwesome in various components

- src/Frontend/src/components/audit/AuditList.vue
- src/Frontend/src/components/audit/AuditListItem.vue
- src/Frontend/src/components/audit/MessageStatusIcon.vue
This pull request refactors the status display logic in the `AuditList` component by introducing new `AuditListItem` and `MessageStatusIcon` components. This change improves code modularity and maintainability by encapsulating status-related logic and styles into a dedicated component.
> Refactor AuditList component to use new MessageStatusIcon component

- src/Frontend/src/components/audit/AuditListItem.vue
So that we can easily open indivdual messages in a new tab.
> Make row links proper a tags

- .github/workflows/release.yml
After the switch from Dependabot to Renovate, Renovate has the secrets to create signed Windows installers and other artifacts, so there's no need to check for the Dependabot actor which would not have those secrets.
> No point in checking for Dependabot PRs anymore

- src/Frontend/src/components/audit/AuditMenuItem.vue
- src/Frontend/src/components/configuration/ConfigurationMenuItem.vue
- src/Frontend/src/components/customchecks/CustomChecksMenuItem.vue
- src/Frontend/src/components/dashboard/DashboardMenuItem.vue
- src/Frontend/src/components/events/EventsMenuItem.vue
- src/Frontend/src/components/failedmessages/FailedMessagesMenuItem.vue
- src/Frontend/src/components/heartbeats/HeartbeatsMenuItem.vue
- src/Frontend/src/components/monitoring/MonitoringMenuItem.vue
- src/Frontend/src/views/throughputreport/ThroughputMenuItem.vue
Menu icons were expected to show tooltips via the 'title' prop passed to the FontAwesome Vue component. However, the internal SVG <title> tag did not trigger native browser tooltips as intended.
This PR replaces the use of 'title' with Tippy.js to ensure consistent tooltip behavior across browsers and improve accessibility. Tooltips now appear reliably on hover.
> Menu icon tooltips not displaying as expected via FontAwesome title attribute

- src/Frontend/src/components/FAIcon.vue
- src/Frontend/src/components/audit/AuditMenuItem.vue
- src/Frontend/src/components/configuration/ConfigurationMenuItem.vue
- src/Frontend/src/components/customchecks/CustomChecksMenuItem.vue
- src/Frontend/src/components/dashboard/DashboardMenuItem.vue
- src/Frontend/src/components/events/EventsMenuItem.vue
- src/Frontend/src/components/failedmessages/FailedMessagesMenuItem.vue
- src/Frontend/src/components/heartbeats/HeartbeatsMenuItem.vue
- src/Frontend/src/components/monitoring/MonitoringMenuItem.vue
- src/Frontend/src/views/throughputreport/ThroughputMenuItem.vue
Follow through on https://github.com/Particular/ServicePulse/pull/2615
> FAIcon component tweaks
