Particular/ServicePulse

src/ServicePulse.Host.Tests/CommandLineTests/CaseLessOptionSetTests.cs
src/ServicePulse.Host.Tests/CommandLineTests/HostArgsTests.cs
src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
src/ServicePulse.Host/Hosting/CaseLessOptionSet.cs
src/ServicePulse.Host/Hosting/Help.txt
src/ServicePulse.Host/Hosting/HostArguments.cs
src/ServicePulse.Host/Properties/AssemblyInfo.cs
src/ServicePulse.Host/ServicePulse.Host.csproj

Add command line validation

---

src/ServicePulse.Host/app/js/app.constants.js
src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.js
src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
src/ServicePulse.Host/app/js/services/services.platform-update.js

@johnsimons @mikeminutillo please review

Alerts User to Upgrade ServiceControl

---

src/ServicePulse.Host/app/css/style.css
src/ServicePulse.Host/app/js/dashboard/dashboard.html
src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.tpl.html
src/ServicePulse.Host/app/js/services/services.semver.js
src/ServicePulse.Host/app/layout/sidebar.html

Upgrade servicecontrol link

---

src/ServicePulse.Host/app/NoIE.html

I came across the noie message when I was assisting a customer with an issue.

Make the NoIE help slightly better

---

src/ServicePulse.Host/app/css/app.css
src/ServicePulse.Host/app/css/style.css
src/ServicePulse.Host/app/js/endpoints/endpoints.controller.js

In response to a customer inquiry
fixes https://github.com/Particular/ServicePulse/issues/256
Moved some css to tidy up

endpoint overview time update

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/layout/navbar.html

Fixing navbar for resizing

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/directives/ui.particular.confirmclick.js
src/SmokeTest.Server/MyHandler.cs

fixes 
- [Overrun on long names on message group screen](https://github.com/Particular/ServicePulse/issues/294)

hotfix-1.4.1

---

src/ServicePulse.Host/app/js/app.controller.js

Fixes https://github.com/Particular/ServicePulse/issues/326
cc @petersgiles

Use uri join for signalRListener

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/app.http.js
src/ServicePulse.Host/app/js/views/dashboard/dashboard.html

fixes #334 by removing headers which seem to cause issues when hosting in IIS. I didn't see any impact by this change when hosting with Nancy?
also changed the links on the dashboard to use relative urls (like the navbar) so it works correctly with virtual directories.
@Particular/servicepulse-maintainers @petersgiles @colin-higgins @WojcikMike please review

Fix Route Change Error when hosting in IIS

---

src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
src/ServicePulse.Host.Tests/VerifyAppConstantsJSTextReplacement.cs
src/ServicePulse.Host.Tests/packages.config

Updating Nunit to v3

---

src/ServicePulse.Host/app/index.html

Fixes https://github.com/Particular/ServicePulse/issues/354

Changed NoIE html url to not force root

---

src/ServicePulse.Host/app/js/app.controller.js

Hiding mobile navigation when the link is clicked

---

src/ServicePulse.Host/app/js/directives/ui.particular.configurationTabs.tpl.html
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.js
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
src/ServicePulse.Host/app/js/views/archive/controller.js
src/ServicePulse.Host/app/js/views/archive/route.js
src/ServicePulse.Host/app/js/views/archive/view.html
src/ServicePulse.Host/app/js/views/configuration/configuration.route.js
src/ServicePulse.Host/app/js/views/custom_checks/customChecks.route.js
src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
src/ServicePulse.Host/app/js/views/event_log_items/eventLogItems.js
src/ServicePulse.Host/app/js/views/failed_groups/controller.js
src/ServicePulse.Host/app/js/views/failed_groups/route.js
src/ServicePulse.Host/app/js/views/failed_messages/controller.js
src/ServicePulse.Host/app/js/views/failed_messages/route.js
src/ServicePulse.Host/app/js/views/failed_messages/view.html
src/ServicePulse.Host/app/js/views/message/route.js
src/ServicePulse.Host/app/js/views/pending_retries/route.js
src/ServicePulse.Host/app/js/views/pending_retries/view.html
src/ServicePulse.Host/app/js/views/redirect/route.js
src/ServicePulse.Host/app/layout/navbar.html

Connects to #402
This is a change that modify almost all routes to new ones. I added routes to redirect from old url to new ones. 
@Particular/servicecontrol-maintainers please review

Change url structure

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/failed_groups/view.html

Enlarge group retry dismiss button

---

src/ServicePulse.Host/app/js/views/failed_groups/controller.js
src/ServicePulse.Host/app/js/views/failed_groups/view.html

fixes #420
cc: @Particular/servicepulse-maintainers please review and merge

When clicking on dismiss button stopping click propagation

---

src/ServicePulse.Host/app/js/services/services.service-control.js
src/ServicePulse.Host/app/js/views/failed_groups/controller.js
src/ServicePulse.Host/app/js/views/failed_groups/view.html

Added dismissal code @WojcikMike.
Check if you're happy and you and merge into your branch

Require dismissal of archive operations

---

docs/releasing.md

@Particular/servicecontrol-maintainers please have a look

Updating the release notes documentation

---

src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.html
src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.module.js

Changes:
1. Changed attribute directive to element directive
2. Load data points from binding instead of hardcoded in directive

Change attribute to element

---

README.md
src/ServicePulse.Host.Tests/README.md

@Particular/servicepulse-maintainers please review and merge

Adding set up information to projects readme.

---

src/ServicePulse.Host.Tests/tests/js/services/services.monitoring.spec.js
src/ServicePulse.Host/app/js/services/services.monitoring.js
src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.controller.js

targets #450 
based on todays call with @WojcikMike @Scooletz and @sergioc, this code changes the service to not load and aggregate data from SC for now and limit itself to data from the monitoring server.
thoughts?

Only load monitoring data from monitoring overview

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.js
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html

Revised style of counts for failed msg tabs

---

src/ServicePulse.Host/app/css/particular.css

Connects to #452 
@Particular/servicecontrol-maintainers review and merge

Increase breakpoint to show collapsed nav

---

README.md

@Particular/servicepulse-maintainers please review and merge

Adding a section about installing node.js to README.md

---

src/ServicePulse.Host/app/layout/navbar.html

Adds the old endpoints page back for now.

Add old endpoints page back

---

src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.module.js

show the value of the average in the vertical middle on the right side of the graph
note that it doesn't contain any trimming logic and just cuts off large values (e.g. second last graph is 8 millions)
ping @WojcikMike @WilliamBZA @sergioc

Show average number

---

src/ServicePulse.Host.Tests/tests/js/services/services.monitoring.spec.js
src/ServicePulse.Host/app/js/services/services.monitoring.js
src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.controller.js
src/ServicePulse.Host/app/js/views/monitored-endpoints/monitored-endpoints.html

Changes to the new json format

Change to new json format

---

src/ServicePulse.Host.Tests/tests/js/services/services.monitoring.spec.js
src/ServicePulse.Host/app/js/directives/ui.particular.graph.js
src/ServicePulse.Host/app/js/services/services.monitoring.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.module.js

Shows the graphs from the specific instances.
Requires the monitoring server changes too.
Expects a JSON result like:
```json
[  
{  
"name":"test@machine2",
"id":"test@machine2",
"processingTime":{  
"xValues":[  
],
"average":0,
"points":[  
]
},
"criticalTime":{  
"average":2.5714285714285716,
"points":[  
0.33333333333333331,
1.8,
3,
4.5,
5,
0,
1,
2.5,
2,
2.6666666666666665,
3,
4.5,
0,
1.5,
3,
4.5,
0,
0,
0,
0
]
}
},
{  
"name":"test@machine",
"id":"test@machine",
"processingTime":{  
"xValues":[  
0,
1,
4,
9,
16,
25,
36,
49,
64,
81,
100,
121,
144,
169,
196,
225,
256,
289,
324,
361
],
"average":2.5714285714285716,
"points":[  
0.33333333333333331,
1.8,
3,
4.5,
5,
0,
1,
2.5,
2,
2.6666666666666665,
3,
4.5,
0,
1.5,
3,
4.5,
0,
0,
0,
0
]
},
"criticalTime":{  
"average":0,
"points":[  
]
}
} …
```

Show instance graphs

---

src/ServicePulse.Host/app/js/directives/ui.particular.graph.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Fixes https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/120
Fixes https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/121
Fixes https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/125

Scale and average

---

src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
src/ServicePulse.Host.Tests/SpecsRunner.html
src/ServicePulse.Host.Tests/tests/js/_references.js
src/ServicePulse.Host.Tests/tests/js/directives/ui.particular.largenumber.spec.js
src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
src/ServicePulse.Host/app/js/directives/ui.particular.js
src/ServicePulse.Host/app/js/directives/ui.particular.largenumber.js
src/ServicePulse.Host/app/js/services/services.service-control.js
src/ServicePulse.Host/app/js/views/archive/view.html
src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/failed_messages/controller.js
src/ServicePulse.Host/app/js/views/failed_messages/route.js
src/ServicePulse.Host/app/js/views/failed_messages/view.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.controller.js
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html
src/ServicePulse.Host/app/layout/navbar.html

Shows an error indicator for a logical endpoint on the monitoring page

Show failed message indicator

---

README.md

Improved outline and added Git dependency.

Update package manager instructions

---

src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Adding diagram to display throughput

Adding throughput

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Shows a staleness warning if required

Show stale data warning icon

---

src/ServicePulse.Host.Tests/CommandLineTests/HostArgsTests.cs
src/ServicePulse.Host/Commands/ExtractAndUpdateConstantsCommand.cs
src/ServicePulse.Host/Commands/ExtractCommand.cs
src/ServicePulse.Host/Hosting/HostArguments.cs
src/ServicePulse.Host/app/js/app.constants.js
src/ServicePulse.Install.CustomActions/CustomAction.cs
src/Setup/ServicePulse.aip

This PR adds the possibility to configure url for ServiceControl.Monitoring.

Adding to installer url for Monitoring

---

src/ServicePulse.Host/Commands/ExtractAndUpdateConstantsCommand.cs
src/ServicePulse.Install.CustomActions/CustomAction.cs

@WilliamBZA that i the fix for the regex to properly add ' to the url

Fixing issue with regex

---

src/ServicePulse.Host.Tests/tests/js/services/services.monitoring.spec.js
src/ServicePulse.Host/app/js/services/services.monitoring.js
src/ServicePulse.Host/app/js/services/services.service-control.js
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.controller.js
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Fixes the tests by changing them to async and flushing the mocked http requests asynchronously

Change tests to async flush

---

src/ServicePulse.Host.Tests/SpecsRunner.html
src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/directives/ui.particular.js
src/ServicePulse.Host/app/js/directives/ui.particular.largeGraph.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html

Adding big graph on the details screen

Add big graph

---

src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html

@tmasternak @WilliamBZA please have a look

Swapping order of the tabs Message Types/Instances

---

src/ServicePulse.Host.Tests/SpecsRunner.html
src/ServicePulse.Host.Tests/tests/js/directives/ui.particular.largenumber.spec.js
src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/directives/ui.particular.duration.js
src/ServicePulse.Host/app/js/directives/ui.particular.graph.js
src/ServicePulse.Host/app/js/directives/ui.particular.graphdecimal.js
src/ServicePulse.Host/app/js/directives/ui.particular.graphduration.js
src/ServicePulse.Host/app/js/directives/ui.particular.js
src/ServicePulse.Host/app/js/directives/ui.particular.largenumber.js
src/ServicePulse.Host/app/js/services/service.formatter.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.controller.js
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Don't forget to run `bower install` to download the latest bower requirements (side note: we should move away from bower to vanilla npm I think).

Number formatting

---

src/ServicePulse.Host/app/js/directives/ui.particular.largeGraph.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js

Making the tooltip look nicer and display unit for value

---

src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.controller.js

This reapplies changes that were introduced in #508

Force scope refresh on Monitored Endpoints observer value 

---

src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js

This is partial solution to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/270.
Now the page renders but metrics data is not properly refreshed.

Polyfills for Array.findIndex and Array.fill

---

src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.html
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.html

Updating tooltips for metrics

---

src/ServicePulse.Host/app/js/services/constant.historyperiods.js
src/ServicePulse.Host/app/js/services/services.monitoring.js
src/ServicePulse.Host/app/js/views/endpoint_details/endpoint_details.controller.js
src/ServicePulse.Host/app/js/views/monitored_endpoints/monitored_endpoints.controller.js

@WilliamBZA @tmasternak this pr shouldn't be merged before SC.Monitorig change. As sending a request with 1 minute period cause an exception in SC.Monitoring

Adding period of 1 minute. Changing frequency of refresh

---

src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Critical and Processing times values swapped under big graph

---

src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/modules/monitoring/js/constant.diagrams.js
src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.graph.js
src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.largeGraph.js
src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.module.js
src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.module.js
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

@tmasternak please have a look

Adding configuration for minimum y axis scale

---

src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Fixing typo in processingTime binding

Fixing processing time unit rendering under big graph

---

src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js

This PR handles Monitoring connectivity issues in a similar way that we handle them for SC.
The notification pop-up is shown that can be dismissed. To reconnect page refresh is needed.

Notification pop-up on connectivity problems

---

src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Removing duplicated AVG in the processing time value on endpoint details screen.

Removing duplicated AVG in Processing Time 

---

src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html

Hiding the badge where there's no failed message

---

src/ServicePulse.Host/app/js/views/message/controller.js
src/ServicePulse.Host/app/js/views/message/messages-view.html

Making the error message for message screen more descriptive

---

src/ServicePulse.Host/app/js/views/failed_messages/controller.js

Removing arrow functions from failed message screen

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

This fixes a bug when icons overlayed endpoint name

Fixing the issue when icons overlayed the endpoint name 

---

src/ServicePulse.Host/app/js/views/configuration/configuration.html

Typo heartbeat

---

src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.controller.js
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Addresses: https://github.com/Particular/ServicePulse/issues/652

Add tab to url

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/views/configuration/configuration.html
src/ServicePulse.Host/app/js/views/dashboard/dashboard.html
src/ServicePulse.Host/app/js/views/event_log_items/eventLogItems.tpl.html
src/ServicePulse.Host/app/js/views/failed_groups/view.html
src/ServicePulse.Host/app/layout/footer.html
src/ServicePulse.Host/app/layout/navbar.html
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Min width 1440px

---

src/ServicePulse.Host/app/js/services/service.formatter.js

Correlates to: https://github.com/Particular/PlatformDevelopment/issues/2250

Change to sec

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/modules/monitoring/js/services/services.monitoring.js
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

fixes: https://github.com/Particular/PlatformDevelopment/issues/1881

Filtering out system messages

---

src/Setup/ServicePulse.aip

Reverts Particular/ServicePulse#675

Revert "Add installer connectivity test buttons"

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/configuration/configuration.html
src/ServicePulse.Host/app/layout/footer.html
src/ServicePulse.Host/app/modules/monitoring/js/directives/ui.particular.monitoringConnectivityStatus.tpl.html

Pre release fixes

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/failed_messages/controller.js

fixes https://github.com/Particular/ServicePulse/issues/694

Replace string template literals with vanilla string concatenation

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/app.bootstrap.js
src/ServicePulse.Host/app/js/app.controller.js

Adds a screen at load if ServiceControl is not accessible.
It would probably be better with a static image instead of the same animated gif.

Add can't connect screen

---

src/ServicePulse.Host.Tests/tests/js/views/message/controller.spec.js
src/ServicePulse.Host/app/js/views/message/controller.js

@WilliamBZA please have a look. I am not conviced about this

Adding nasty tests to verify the change

---

src/ServicePulse.Host.Tests/tests/js/views/message/controller.spec.js
src/ServicePulse.Host/app/js/views/message/controller.js

Don't throw on missing header

---

README.md
src/ServicePulse.Host/package.json

Adds http`server dev-dependency so that users can develop without Visual Studio
@mauroservienti this is what I was talking about

Add http server

---

src/ServicePulse.Host/app/js/views/failed_groups/view.html

fixes https://github.com/Particular/ServicePulse/issues/704

Removing / from the beginning of the URL 

---

src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/polyfill/string.prototype.endsWith.js

Adds a polyfill for endsWith which is not supported in IE.

Add polyfill for endsWith

---

src/ServicePulse.Host/app/js/views/failed_messages/view.html

Fixes https://github.com/Particular/ServicePulse/issues/760

Stop displaying duplicate messages

---

src/ServicePulse.Host/.eslintrc.js
src/ServicePulse.Host/app/js/app.bootstrap.js
src/ServicePulse.Host/package.json

I had a few spare minutes and added ESLint.
It's not set to run permanently yet, but as time goes on we might be able to clean up enough files to include it as part of the build.

Add ESLint

---

src/ServicePulse.Host/app/js/views/archive/view.html
src/ServicePulse.Host/app/js/views/failed_messages/view.html
src/ServicePulse.Host/app/js/views/pending_retries/view.html

Fixes eager infinite scroll issue

---

src/ServicePulse.Host/app/js/services/services.service-control.js
src/ServicePulse.Host/app/js/views/archive/controller.js
src/ServicePulse.Host/app/js/views/message/controller.js
src/ServicePulse.Host/app/js/views/message/editor/messageEditorModal.controller.js

Fixes incorrect headers issues

---

src/ServicePulse.Host/app/css/particular.css

Fixes missing checkbox on adding redirect

---

src/ServicePulse.Host/app/js/views/failed_messages/view.html
src/ServicePulse.Host/app/js/views/message/messages-view.html
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Fixes https://github.com/Particular/ServicePulse/issues/650
Browser back is plenty sufficient.
Also we dont have these breadcrumb navigation links in all the pages.
Removed it to be consistent.
Co-authored-by: Kyle Baley<kyle.baley@particular.net>

Removed the breadcrumb navigation.

---

src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/polyfill/array.prototype.includes.js

@indualagarsamy @kbaley @mikeminutillo hey folks. I saw that you will be releasing today so I went ahead and tested the SP in IE as this is something that causes us problems. I found this issue with edit and retry. I know that it was not your change but I provided a fix regardless. It took me 10 mins.

Adding a polyfil for includes so that edit and retry works on IE.

---

src/ServicePulse.Host/app/js/app.controller.js
src/ServicePulse.Host/app/js/views/endpoints/endpoints.controller.js
src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
src/ServicePulse.Host/app/modules/configuration/js/configuration.controller.js
src/ServicePulse.Host/app/modules/configuration/js/configuration.service.js

Fixes https://github.com/Particular/ServicePulse/issues/756
2 commits. One to change the config service to es6, and the second to actually implement the required change.

Allow for the deletion of endpoints

---

README.md

@kbaley please have a look.
William if you feel like adding something here, go ahead.

Providing some description of npm scripts

---

src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Shows the sum of the throughput for all endpoints in the tooltip.

Show total throughput in tooltip

---

GitVersion.yml
src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/Setup/Setup.csproj

Update Particular.Packaging in master

---

GitVersion.yml
src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/Setup/Setup.csproj

Update Particular.Packaging in release-1.20

---

GitVersion.yml
src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/Setup/Setup.csproj

Update Particular.Packaging in release-1.21

---

GitVersion.yml
src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/Setup/Setup.csproj

Update Particular.Packaging in release-1.22

---

GitVersion.yml
src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/Setup/Setup.csproj

Update Particular.Packaging in release-1.23

---

src/ServicePulse.Host/app/js/services/services.breadcrumbs.js
src/ServicePulse.Host/app/js/services/services.exception-handler.js
src/ServicePulse.Host/app/js/services/services.semver.js
src/ServicePulse.Host/app/js/views/dashboard/dashboard.controller.js
src/ServicePulse.Host/app/lib/page-width-functions.js
src/ServicePulse.Host/app/modules/configuration/connectionsManager.js
src/ServicePulse.Host/app/modules/configuration/js/configuration.service.js
src/ServicePulse.Host/app/modules/configuration/js/directives/ui.particular.configurationTabs.js
src/ServicePulse.Host/app/modules/shell/js/licensenotifier/license.notifier.js

Fixing some lint errors in the SP

Fixing some lint errors from the code

---

LICENSE.md
THIRD-PARTY-NOTICES.txt
src/ServicePulse.Host/Owin/Microsoft/Constants.cs
src/ServicePulse.Host/Owin/Microsoft/FileExtensionContentTypeProvider.cs
src/ServicePulse.Host/Owin/Microsoft/FileInfo.cs
src/ServicePulse.Host/Owin/Microsoft/StaticFileContext.cs
src/ServicePulse.Host/Owin/Microsoft/StreamCopyOperation.cs

Based on https://github.com/aspnet/SignalR/blob/master/THIRD-PARTY-NOTICES

Moved third party licenses to its own notice file

---

.reposync.yml

Closes https://github.com/Particular/ServicePulse/pull/843
Closes https://github.com/Particular/ServicePulse/pull/842

Exclude snk from sync

---

.gitignore
src/.gitignore

Fixes https://github.com/Particular/ServicePulse/pull/846
Unable to run javascript unittests on my box. Not certain where "Chutzpah" is creating those files but for now assuming its within the sln or project folder
Edit: 
Ok, 'Chutzpah' files are created in the folder that contains the test so the ignore in the src folder works

Reposync fixes - Moved ignores

---

src/ServicePulse.Host/app/js/views/event_log_items/eventLogItems.js

Addresses: https://github.com/Particular/ServicePulse/issues/812

Adding an redirect to event related to failed messages.

---

src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
src/ServicePulse.Host/app/modules/monitoring/views/monitoring_no_data.html
src/ServicePulse.Host/app/modules/monitoring/views/monitoring_not_available.html

Resolves #755
No connectivity:
No data:

Distinction between "no connection" and "no data" and improved troubleshooting hints

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/views/endpoints/endpoints.controller.js
src/ServicePulse.Host/app/js/views/endpoints/endpoints.html

Fixes https://github.com/Particular/ServicePulse/issues/153
Adds a dropdown for sort options, and adds a textbox to filter the list of endpoints.
@sergioc I need some help with the styling of the text box please. I can't seem to get it to look like it belongs.

Add sort and filter to endpoints screen

---

src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/app.js
src/ServicePulse.Host/app/js/views/event_log_items/eventLogItems.tpl.html
src/ServicePulse.Host/app/layout/navbar.html
src/ServicePulse.Host/app/modules/configuration/js/configuration.route.js
src/ServicePulse.Host/app/modules/shell/js/events.controller.js
src/ServicePulse.Host/app/modules/shell/js/events.module.js
src/ServicePulse.Host/app/modules/shell/js/events.route.js
src/ServicePulse.Host/app/modules/shell/js/services/service.auditLog.js
src/ServicePulse.Host/app/modules/shell/shell.js
src/ServicePulse.Host/app/modules/shell/views/events-view.html

Two screenshots are screaming for Sergios Attention:
Link on the dashboard:
And event page:
At the moment there is no other way to get to that page than through the link, I think it should be available from the menu, but I have no good idea where should it reside.

Create event log screen

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Depends on https://github.com/Particular/ServiceControl/pull/1989

Show the number of instances with connectivity problems on the monitoring overview screen

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Use endpoint instances count only

---

src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Makes sure the functionality still works with older versions of SC Monitoring

Make sure counts are backwards compatible

---

src/ServicePulse.Host/app/js/app.controller.js
src/ServicePulse.Host/app/js/directives/ui.particular.productVersion.js

Fixes https://github.com/Particular/ServicePulse/issues/889

Remove arrow functions to support IE

---

src/ServicePulse.Host/app/js/services/factory.listener.js

Fixes https://github.com/Particular/ServicePulse/issues/897
Also logs to the console what the connect error was (this is an attempt to get more debug information for a support case)

Retry to connect if first connection fails

---

src/ServicePulse.Host/app/js/app.controller.js

Cherry-pick for release branch

Remove arrow function in appctrl

---

src/ServicePulse.Host.Tests/VerifyAppConstantsJSTextReplacement.cs
src/ServicePulse.Host/app/js/services/services.platform-update.js

Retrieve platform updates over HTTPS

---

src/ServicePulse.Host.Tests/karma.conf.js
src/ServicePulse.Host.Tests/package-lock.json
src/ServicePulse.Host.Tests/package.json
src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/js/.eslintrc.js
src/ServicePulse.Host/app/js/services/factory.listener.js
src/ServicePulse.Host/package.json

Verified that an arrow function breaks the build on TeamCity - the last commit fixes that.

Run ESLint as part of CI, with js directory targeted to ES5

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/app.controller.js
src/ServicePulse.Host/app/modules/shell/js/events.controller.js
src/ServicePulse.Host/app/modules/shell/views/events-view.html

Events page size

---

src/ServicePulse.Host/app/modules/monitoring/js/services/services.messageTypeParser.js
src/ServicePulse.Host/app/modules/monitoring/views/endpoint_details.html

Shorten message names to show only message types and cater for nested classes

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.controller.js
src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html

Adds a text input field that allows filtering endpoints by their name. In addition the filter can also be provided via search param in the URL so that filters can be shared and saved via bookmarks.
This is a draft PR, missing proper styling and more.

Endpoint filtering for monitoring view

---

src/ServicePulse.Host.Tests/tests/js/views/message/controller.spec.js
src/ServicePulse.Host/app/js/app.controller.js
src/ServicePulse.Host/app/js/directives/ui.particular.failedMessageTabs.tpl.html
src/ServicePulse.Host/app/js/services/services.service-control.js
src/ServicePulse.Host/app/js/views/archive/archive-view.html
src/ServicePulse.Host/app/js/views/archive/controller.js
src/ServicePulse.Host/app/js/views/archive/route.js
src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.html
src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.route.js
src/ServicePulse.Host/app/js/views/failed_groups/controller.js
src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html
src/ServicePulse.Host/app/js/views/failed_messages/controller.js
src/ServicePulse.Host/app/js/views/failed_messages/failed-messages-view.html
src/ServicePulse.Host/app/js/views/message/controller.js
src/ServicePulse.Host/app/js/views/message/messages-view.html

Replaced 'archive' with 'delete' and changed icon to be trash icon

---

src/ServicePulse.Host/app/js/views/archive/archive-view.html

(cherry picked from commit 6d4bac5e68281877d2e08d3f9aa658eb288844d4)

Small cleanup

---

src/builddockerimages.ps1
src/dockerfile.iis
src/dockerfile.nginx
src/nginx.conf

Adds dockerfiles for iis and nginx.
To build the linux image:
`docker build -f .\dockerfile.nginx -t particular/servicepulse.nginx .\`
To run the linux image:
`docker run --name servicepulselinux -p 9292:90 -d particular/servicepulse.nginx`
To access the linux instance:
Open browser to `http://localhost:9292`
To build the iis image:
`docker build -f .\dockerfile.iis -t particular/servicepulse.iis .`
To run the iis image:
`docker run --name servicepulse -p 9393:80 -d particular/servicepulse.iis`
To access the iis instance:
Open browser to `http://localhost:9393`.

Add docker files for iis and nginx

---

src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html

Closes https://github.com/Particular/ServicePulse/issues/744

Added general title for retried messages without a group.

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/virus-scan.yml
src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
src/ServicePulse.Host.Tests/package-lock.json
src/ServicePulse.Host.Tests/package.json
src/ServicePulse.Host/app/modules/monitoring/js/endpoint_details.module.js
src/ServicePulse.Host/app/modules/monitoring/js/monitored_endpoints.module.js
src/Setup/ServicePulse.aip
src/Setup/Setup.csproj

Add GitHub Actions

---

src/ServicePulse.Host/app/js/app.controller.js
src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.controller.js
src/ServicePulse.Host/app/js/views/archivedgroups/archivedgroups.html
src/ServicePulse.Host/app/js/views/failed_groups/service.js

Adding a UI to allow for group unarchive

---

README.md

https://discuss.particular.net/t/retire-support-for-internet-explorer-in-service-pulse/2131

Remove IE as per announcement

---

src/ServicePulse.Host/app/css/particular.css
src/ServicePulse.Host/app/js/views/pending_retries/pending-retries-view.html

tip to enable auditing to view processing status

---

src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Host/app/index.html
src/ServicePulse.Host/app/js/services/services.export.js
src/ServicePulse.Host/app/js/services/services.module.js
src/ServicePulse.Host/app/js/views/failed_messages/controller.js
src/ServicePulse.Host/app/js/views/message/controller.js
src/ServicePulse.Host/app/js/views/message/messages-view.html

In addition for https://github.com/Particular/ServicePulse/issues/850

Added an export for failed message details

---

.github/workflows/release.yml
src/Setup/ServicePulse.aip
src/Setup/Setup.csproj
src/Setup/commands.aic

This PR converts the signing of the installer and NuGet packages to use a certificate stored in Key Vault, which enables us to use an EV code signing certifcate.

Signing with KeyVault

---

src/Setup/Setup.csproj

Fix minver patch version

---

src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html

Hide note box when no note is present

---

src/ServicePulse.Host/app/js/services/services.service-control.js

fixes: https://github.com/Particular/ServicePulse/issues/1248

Fixing the getBody to only apply transform when body is a json

---

src/ServicePulse.Host.Tests/tests/js/services/service.formatter.spec.js
src/ServicePulse.Host/app/js/services/service.formatter.js
src/ServicePulse.Host/package.json

Timespan sparkline values show 'Invalid date' when displaying HR unit values bug fix

---

src/Particular.PlatformSample.ServicePulse/Particular.PlatformSample.ServicePulse.csproj
src/ServicePulse.Host.Tests/ServicePulse.Host.Tests.csproj
src/ServicePulse.Host/ServicePulse.Host.csproj
src/ServicePulse.Install.CustomActions/ServicePulse.Install.CustomActions.csproj
src/Setup/Setup.csproj
src/SmokeTest.3rdParty/SmokeTest.3rdParty.csproj
src/SmokeTest.Client/SmokeTest.Client.csproj
src/SmokeTest.ClientNoHeartbeat/SmokeTest.ClientNoHeartbeat.csproj
src/SmokeTest.Server/SmokeTest.Server.csproj
src/SmokeTest.Shared/SmokeTest.Shared.csproj
src/SmokeTest.SignalrClient/SmokeTest.SignalrClient.csproj

Update all projects to the same .NET version - 4.8

Update to .NET 4.8

---

.github/workflows/ci.yml
.github/workflows/release.yml

Update set output

---

src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/components/TimeSince.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/LastTenOperations.vue
src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

The PR creates a component in vue that displays a dropdown view of the last 10 message group retries.

Last ten operations dropdown - vue

---

src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/DashboardItem.vue
src/ServicePulse.Host/vue/src/components/EventItemShort.vue
src/ServicePulse.Host/vue/src/views/DashboardView.vue

Once https://github.com/Particular/ServicePulse/pull/1376 is merged this can be re targeted to the working branch

Update dashboard to use bootstrap 5 styling

---

src/ServicePulse.Host/vue/src/components/TimeSince.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupDelete.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupRetry.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
src/ServicePulse.Host/vue/src/composables/serviceMessageGroup.js

This PR has the following functionalities.
* Delete group
* Retry group
Replaces https://github.com/Particular/ServicePulse/pull/1385

Vue delete groups

---

src/ServicePulse.Host/vue/index.html
src/ServicePulse.Host/vue/package-lock.json
src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/App.vue
src/ServicePulse.Host/vue/src/assets/dropdown.css
src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/GroupAndOrderBy.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
src/ServicePulse.Host/vue/src/composables/serviceFailedMessageClassification.js
src/ServicePulse.Host/vue/src/composables/serviceFailedMessageGroupSortings.js
src/ServicePulse.Host/vue/src/composables/serviceMessageGroup.js
src/ServicePulse.Host/vue/src/views/ConfigurationView.vue

Adds the headings for the all failed messages page.
Needs https://github.com/Particular/ServicePulse/pull/1387 merged for styles already included in there

Add all failed messages headings

---

src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupRestore.vue
src/ServicePulse.Host/vue/src/composables/serviceMessageGroup.js
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

Replaces https://github.com/Particular/ServicePulse/pull/1395
This PR contains the functionality of the following wrt the Deleted Message Groups Tab
- Display all deleted message groups 
- Restore the group

display deleted message groups, restore group - basic screens

---

src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue

- Checks the content type before trying to deserialize it
- Prettifies the body based on the content-type

Show XML and JSON bodies

---

src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue

- Keeps the note in memory until servicecontrol returns a note for the same group.
- Clears the list when the classifier changes

Keep comments in memory until saved by server

---

src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/router/index.js

This PR on the deleted messages has the following.
- Filter by period
- navigate to deleted messages from the deleted message group page

Vue all deleted msgs

---

src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

This PR has the following changes in the deleted messages screen
- Display scheduled deletion time 
- Display retry badge

Display scheduled deletion time and retry badge on all deleted messages

---

src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/ConfirmDialog.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupNoteEdit.vue

Adds the `modal-open` class to the body when a modal is opened.

Add modal-open when modal is open

---

src/ServicePulse.Host/vue/src/components/ConfirmDialog.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue

Trims the pager and has the +- 5 shortcuts

Show shortcuts for pager and trim it

---

src/ServicePulse.Host/vue/src/components/configuration/RetryRedirects.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue

This PR adds tootltip to the message list displayed in the following pages.
- All failed messages, 
- All deleted Messages 
- Retryredirect pages

Add tool tip to messages

---

src/ServicePulse.Host/vue/src/assets/toast.css
src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue

Styles the toast notifications a bit better.
I also tweaked the notifications on the groups page.

Style toast messages

---

src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue

This PR relates to https://github.com/Particular/ServicePulse/pull/1447

make id computed

---

src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue

This prevents the full page refresh on navigation

Use routerlink for edit of navigation instead of a tag

---

src/ServicePulse.Host.Tests/ApprovalFiles/APIApprovals.PlatformSampleApprovals.approved.txt
src/ServicePulse.Host/angular/app/index.html
src/ServicePulse.Host/angular/app/layout/navbar.html
src/ServicePulse.Host/vue/index.html
src/ServicePulse.Host/vue/public/js/app.constants.js
src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/components/configuration/RetryRedirects.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroupNoteEdit.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageList.vue
src/ServicePulse.Host/vue/src/router/index.js
src/ServicePulse.Host/vue/vite.config.js

Fixes https://github.com/Particular/ServicePulse/issues/1375
Allows specifying the sub-path within the app.constants.js file. It doesn't seem like we can easily make this transparent.
This will need documentation updates. Specifically on the reverse proxy stuff.

Allow specifying subpath

---

src/ServicePulse.Host/vue/src/assets/toast.css
src/ServicePulse.Host/vue/src/components/EventItemShort.vue
src/ServicePulse.Host/vue/src/components/ToastPopup.vue
src/ServicePulse.Host/vue/src/components/configuration/EndpointConnection.vue
src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications.vue
src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
src/ServicePulse.Host/vue/src/components/configuration/PlatformLicense.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
src/ServicePulse.Host/vue/src/router/index.js
src/ServicePulse.Host/vue/src/views/ConfigurationView.vue

Fixes the navigation in subfolders

Use javascript:void(0) instead of #

---

.github/workflows/release.yml

Cherry pick of all the changes to master to get the release working

Master cherry pick

---

src/ServicePulse.Host/angular/app/modules/shell/js/events.controller.js
src/ServicePulse.Host/vue/src/components/EventItemShort.vue
src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/router/index.js
src/ServicePulse.Host/vue/src/views/DashboardView.vue

This PR fixes the links in 
- Dashboard page  
- View all events page
- Configuration-License

Switch to failed messages link to vue components

---

README.md

Remove '>' from commands so that the copied code is correct.

Fix commands in the README.md

---

src/ServicePulse.Host/angular/app/css/particular.css
src/ServicePulse.Host/angular/app/modules/monitoring/views/endpoint_details.html
src/ServicePulse.Host/angular/app/modules/monitoring/views/monitored_endpoints_list.html
src/ServicePulse.Host/angular/app/modules/monitoring/views/monitored_endpoints_list_grouped.html

Display a toot tip in the endpoint overview and details view if the endpoint is stale or monitoring disconnected

---

src/ServicePulse.Host/vue/src/assets/navbar.css

Backport `Always show the top navigation bar` to 1.36

---

src/ServicePulse.Host/vue/src/assets/navbar.css

Solves https://github.com/Particular/ServicePulse/issues/1507

Always show the top navigation bar

---

src/ServicePulse.Host/vue/src/assets/navbar.css

Backport `Fix navbar alignment when screen less than 992px`

---

src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications_ConfigureEmail.vue

PR to address: [Email notifications don't allow multiple recipients #1079](https://github.com/Particular/ServicePulse/issues/1079)

allow multiple recipient  email address

---

src/ServicePulse.Host/vue/src/components/PageFooter.vue
src/ServicePulse.Host/vue/src/components/ServiceControlNotAvailable.vue
src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js

- The PR to fix - https://github.com/Particular/ServicePulse/issues/1518

fix footer link

---

src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications.vue

This PR addresses https://github.com/Particular/ServicePulse/issues/1552 and fixes the text

Health check notification text

---

src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/components/ServiceControlNotAvailable.vue
src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications_ConfigureEmail.vue
src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

related to TF:
This is just to remove the noise from PRs while migrating the monitoring page to Vue.
- #1572 needs to be merged first

Remove --fix from lint params

---

.github/workflows/ci.yml
.github/workflows/release.yml

related to TF:
Changes:
- Update the actions/setup-node from v2 to v3.8.1
- Remove `NODE_OPTIONS=--openssl-legacy-provider`
- Remove explicit declaration of the default shell for Windows build job

Cleanup workflows

---

src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNoData.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNotAvailable.vue
src/ServicePulse.Host/vue/src/router/index.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

Added a second monitoring header link for Vue. Also added place holder Vue for 'monitoring no data available' and 'monitoring not available'

Added a second page blank for monitoring vue

---

src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNoData.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNotAvailable.vue
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

Fix lint warnings

---

src/ServicePulse.Host/angular/app/layout/navbar.html

Add new monitoring tab for angular for development

---

src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/assets/navbar.css
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

related to TF:
This PR:
- Updates main and navbar CSS
- Adds Endpoint overview header HTML and CSS to the monitoring screen

Add header html to new Vue monitoring endpoint overview screen

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNoData.vue
src/ServicePulse.Host/vue/src/composables/formatter.js
src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js
src/ServicePulse.Host/vue/src/router/index.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

Displays the list of monitored and SC  endpoints.
( this is work in progress)

Endpoint list

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointListGrouped.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringGroupBy.vue
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

related to TF:
This PR:
- Adds the group by component for the monitoring endpoints

Add group by endpoint component for monitoring

---

src/ServicePulse.Host/vue/src/components/monitoring/MonitoringHistroyPeriod.vue
src/ServicePulse.Host/vue/src/composables/serviceHistoryPeriods.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

related to TF:
This PR:
- Creates history selector composable
- Creates history selector component
- Adds component to monitoring view

Monitoring period selector

---

src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/App.vue
src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointListGrouped.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringGroupBy.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringHistoryPeriod.vue
src/ServicePulse.Host/vue/src/main.js

The PR:
- Adds a dependency to popperjs
- Creates an app directive so that all components can use `v-tooltip` with `title`
- Update monitoring pages and components to use `v-tooltip`

Monitoring tooltip display

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue

This PR includes the following,
- Add tooltips to the endpoint details and endpoint list page.
- Remove commented code
- Add history period to endpoint details

Endpointlist details tooltip

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringHistoryPeriod.vue
src/ServicePulse.Host/vue/src/composables/serviceHistoryPeriods.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

This PR renames the text of the element in the period object from 
const periods = [
{ **value**: 1, text: "1m", refreshInterval: 1 * 1000, refreshIntervalText: "Show data from the last minute. Refreshes every 1 second" },
{ **value**: 5, text: "5m", refreshInterval: 5 * 1000, refreshIntervalText: "Show data from the last 5 minutes. Refreshes every 5 seconds" },
{ **value**: 10, text: "10m", refreshInterval: 10 * 1000, refreshIntervalText: "Show data from the last 10 minutes. Refreshes every 10 seconds" },
{ **value**: 15, text: "15m", refreshInterval: 15 * 1000, refreshIntervalText: "Show data from the last 15 minutes. Refreshes every 15 seconds" },
{ **value**: 30, text: "30m", refreshInterval: 30 * 1000, refreshIntervalText: "Show data from the last 30 minutes. Refreshes every 30 …

rename the period value key element

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue

This PR demonstrates applying the idea from this article https://lirantal.com/blog/vuejs-patterns-using-vuejs-3-composition-api-for-reactive-parent-to-child-communication/

Make props reactive

---

src/ServicePulse.Host/vue/src/components/monitoring/D3Graph.vue
src/ServicePulse.Host/vue/src/components/monitoring/D3LargeGraph.vue

Applying the solution described [here](https://lirantal.com/blog/vuejs-patterns-using-vuejs-3-composition-api-for-reactive-parent-to-child-communication/) to make props reactive from changes of a parent component

Making d3graph reactive

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue

This PR fixes the route to endpoint details on history period selection

fix the route to endpoint details on history period selection

---

src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringNotAvailable.vue

This PR fixes css and content for monitoring not available

Display monitoring not available 

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
src/ServicePulse.Host/vue/src/composables/serviceHistoryPeriods.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

Add in the refresh interval for endpoint list and endpoint details page

refresh interval for endpoint details and list page

---

src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/App.vue

Remove explicit call to popperjscore from the project as its built into bootstrap

remove popper as its not being used.

---

src/ServicePulse.Host/angular/app/js/services/services.service-control.js

This PR fixes the issue [Unable to dismiss custom check notification after upgrading SC to 5.0](  https://github.com/Particular/ServicePulse/issues/1675)

fix url to dismiss custom check notification

---

src/ServicePulse.Host/vue/vite.config.js

https://github.com/vuejs/core/tree/main/packages/vue#bundler-build-feature-flags

Fix hydration mismatch

---

src/ServicePulse.Host/vue/.eslintrc.js
src/ServicePulse.Host/vue/package-lock.json
src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/composables/serviceFailedMessage.js

This will cause eslint to require the use of `async`/`await` over `Promise.then` or `Promise.catch`.

Enable no-then ESLint rule

---

src/run-dev.cmd

Adds a cmd file to run the 3 parts of the system needed for development:
- Vue dev server
- Angular dev server
- nginx proxy
I had to go to the readme every day to start up everything but that can be automated :)

Development time convenience

---

src/ServicePulse.Host/vue/.eslintrc.js
src/ServicePulse.Host/vue/package-lock.json
src/ServicePulse.Host/vue/package.json
src/ServicePulse.Host/vue/src/components/EventItemShort.vue
src/ServicePulse.Host/vue/src/components/configuration/EndpointConnection.vue
src/ServicePulse.Host/vue/src/components/configuration/HealthCheckNotifications.vue
src/ServicePulse.Host/vue/src/components/configuration/PlatformConnections.vue
src/ServicePulse.Host/vue/src/components/configuration/RetryRedirects.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/DeletedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/EditMessageHeader.vue
src/ServicePulse.Host/vue/src/components/failedmessages/EditRetryDialog.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessageGroups.vue
src/ServicePulse.Host/vue/src/components/failedmessages/FlowDiagram.vue
src/ServicePulse.Host/vue/src/components/failedmessages/LastTenOperations.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageGroupList.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue
src/ServicePulse.Host/vue/src/components/failedmessages/PendingRetries.vue
src/ServicePulse.Host/vue/src/composables/eventLogItems.js
src/ServicePulse.Host/vue/src/composables/serviceEndpoints.js
src/ServicePulse.Host/vue/src/composables/serviceFailedMessage.js
src/ServicePulse.Host/vue/src/composables/serviceLicense.js
src/ServicePulse.Host/vue/src/composables/serviceMessageGroup.js
src/ServicePulse.Host/vue/src/composables/serviceNotifications.js
src/ServicePulse.Host/vue/src/composables/serviceProductUrls.js
src/ServicePulse.Host/vue/src/composables/serviceRedirects.js
src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js
src/ServicePulse.Host/vue/src/views/ConfigurationView.vue

Migrate promises code to async.
All changes smoke tested. Discovered https://github.com/Particular/ServicePulse/pull/1676 and fixed it on a separate PR.

Migrate to async

---

src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
src/ServicePulse.Host/vue/src/components/failedmessages/PendingRetries.vue

https://github.com/Particular/ServicePulse/pull/1665 added a pagination strip re-usable component. This PR applies the component everywhere in the application where pagination has been added to provide a consistent user experience.

Apply pagination strip

---

src/ServicePulse.Host/vue/src/composables/serviceFailedMessage.ts
src/ServicePulse.Host/vue/src/composables/serviceServiceControlUrls.ts

not sure why the lint did not failed!

Missed 2 files to update throw new Error

---

src/ServicePulse.Host/vue/src/components/failedmessages/FlowDiagram.vue
src/ServicePulse.Host/vue/src/components/failedmessages/MessageView.vue

- Unable to view failed message body
- Flow diagram labels overflow

Smoke test fixes

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue

Adds pagination to message types on the monitoring endpoint details page

Monitoring endpoint details: add Message Type pagination

---

src/ServicePulse.Host/vue/src/assets/main.css
src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
src/ServicePulse.Host/vue/src/components/monitoring/LargeGraph.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringFilter.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringHead.vue
src/ServicePulse.Host/vue/src/components/monitoring/SmallGraph.vue
src/ServicePulse.Host/vue/src/components/monitoring/endpoint.css
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

further extraction of styles pertaining to endpoint lists and details from monitoringview, and customise to suit new layout strategies

Further Monitoring page and endpoint detail CSS

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointBacklog.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointInstances.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointMessageTypes.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointTimings.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointWorkload.vue
src/ServicePulse.Host/vue/src/components/monitoring/formatGraph.js
src/ServicePulse.Host/vue/src/components/monitoring/largeGraphs.css
src/ServicePulse.Host/vue/src/components/monitoring/messageTypes.js
src/ServicePulse.Host/vue/src/stores/MonitoringStore.js

Deconstructs the endpoint details screen into multiple components

Deconstruct endpoint details

---

src/ServicePulse.Host/vue/src/components/monitoring/messageTypes.js
src/ServicePulse.Host/vue/src/stores/MonitoringStore.js

Refactoring monitoring options store to setup store

Convert monitoring store from options to composition API

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointInstances.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointMessageTypes.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringFilter.vue
src/ServicePulse.Host/vue/src/components/monitoring/MonitoringHistoryPeriod.vue
src/ServicePulse.Host/vue/src/stores/MonitoringEndpointDetailsStore.js
src/ServicePulse.Host/vue/src/stores/MonitoringHistoryPeriodStore.js
src/ServicePulse.Host/vue/src/stores/MonitoringStore.js
src/ServicePulse.Host/vue/src/views/MonitoringView.vue

Splits the monitoring store into 3 different stores. One for the history period (shared), one for the list page, and one for the details page.

Split monitoring store

---

src/ServicePulse.Host/vue/src/components/monitoring/EndpointList.vue

Use stores directly in components

---

src/ServicePulse.Host/vue/src/assets/pagination.css
src/ServicePulse.Host/vue/src/components/PaginationStrip.spec.ts
src/ServicePulse.Host/vue/src/components/PaginationStrip.vue
src/ServicePulse.Host/vue/test/utils.ts

The goal of this PR is to showcase a more interesting set of tests for testing **presentation** components. 
The original PR: 
- https://github.com/Particular/ServicePulse/pull/1720
Included the testing setup for testing presentation components and only tested the very basic NoData.vue component. This PR introduces tests for the PaginationStrip

Presentation component tests samples (testing PaginationStrip)

---

src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/composables/isRouteSelected.ts
src/ServicePulse.Host/vue/src/router/index.ts
src/ServicePulse.Host/vue/src/views/ConfigurationView.vue
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

I noticed we had this common functionality that was being reinvented on a bunch of screens, specifically screens with tabs.
This functionality selects the correct tab based on the current route selected.

Refactor subIsActive to a common function

---

src/ServicePulse.Host/vue/src/components/PageHeader.vue
src/ServicePulse.Host/vue/src/composables/isRouteSelected.ts
src/ServicePulse.Host/vue/src/router/config.ts
src/ServicePulse.Host/vue/src/router/index.ts
src/ServicePulse.Host/vue/src/router/routeLinks.ts
src/ServicePulse.Host/vue/src/views/ConfigurationView.vue
src/ServicePulse.Host/vue/src/views/FailedMessagesView.vue

a recent change to checking whether a navitem is active no longer worked for subroutes. This fix returns that functionality

fix navigation items not showing as active for subroutes

---

src/ServicePulse.Host/vue/vite.config.ts

Remove compile-time flags

---

src/ServicePulse.Host/vue/src/components/NoData.vue
src/ServicePulse.Host/vue/src/components/ServiceControlNotAvailable.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointInstances.vue
src/ServicePulse.Host/vue/src/components/monitoring/endpoint.css
src/ServicePulse.Host/vue/src/components/monitoring/messageTypes.ts
src/ServicePulse.Host/vue/vitest.config.ts

fix lingering style issues associated with monitoring migration to Vue

Monitoring css fixes

---

src/ServicePulse.Host/vue/src/assets/footer.css
src/ServicePulse.Host/vue/src/components/monitoring/EndpointInstances.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointListRow.vue
src/ServicePulse.Host/vue/src/components/monitoring/EndpointMessageTypes.vue
src/ServicePulse.Host/vue/src/components/monitoring/endpoint.css
src/ServicePulse.Host/vue/src/router/routeLinks.ts

remove remaining ng- angular template directives, replacing functionality where missing, and unify status warning display

remove leftover angular ng directives

---

src/ServicePulse.Host/vue/src/components/PaginationStrip.spec.ts

Tests for handling case where current page exceeds total page count

---

src/ServicePulse.Host/angular/app/js/services/factory.listener.js
src/ServicePulse.Host/angular/app/js/views/sc_not_available.html
src/ServicePulse.Host/angular/app/layout/footer.html
src/ServicePulse.Host/angular/app/modules/monitoring/js/services/services.connectivityNotifier.js
src/ServicePulse.Host/angular/app/modules/monitoring/views/monitoring_not_available.html

fix links from angular pages to vue connection details and endpoint pages. Addresses issue #1766

fix links from angular pages to vue 

---

src/ServicePulse.Host/vue/src/assets/toast.css

make toast text/icons more visible by changing colour to white and opacity to 1

fix toast contents readability

---

src/ServicePulse.Host/vue/src/components/configuration/RetryRedirectEdit.vue

a couple of fixes resulting from the [typescript refactor](https://github.com/Particular/ServicePulse/pull/1708), but considered worth reviewing separately.

Typescript merge fixes

---

src/ServicePulse.Host/vue/test/driver.ts
src/ServicePulse.Host/vue/test/drivers/vitest/driver.ts
src/ServicePulse.Host/vue/test/specs/monitoring/actions/enterFilterString.ts
src/ServicePulse.Host/vue/test/specs/monitoring/filtering-endpoints.spec.ts
src/ServicePulse.Host/vue/test/specs/monitoring/questions/endpointWithName.ts
src/ServicePulse.Host/vue/test/specs/monitoring/questions/filteredByName.ts

Adds testing for filtering monitoring endpoints

Add automated application tests for filtering monitoring endpoints

---

src/ServicePulse.Host/vue/src/components/failedmessages/FailedMessagesDashboardItem.vue
src/ServicePulse.Host/vue/src/components/heartbeats/HeartbeatsDashboardItem.vue
src/ServicePulse.Host/vue/src/views/DashboardView.vue

This PR moves the remaining dashboard items into dedicated controls.

Refactor dashboard

---

src/ServicePulse.Host/vue/src/components/heartbeats/InactiveEndpoints.vue
src/ServicePulse.Host/vue/src/stores/HeartbeatsStore.ts

implement remove endpoint

---

src/ServicePulse.Host/vue/src/components/heartbeats/HeartbeatsDashboardItem.vue
src/ServicePulse.Host/vue/src/components/heartbeats/HeartbeatsMenuItem.vue
src/ServicePulse.Host/vue/src/composables/serviceServiceControl.ts
src/ServicePulse.Host/vue/src/stores/HeartbeatsStore.ts
src/ServicePulse.Host/vue/test/mocks/heartbeat-endpoint-template.ts
src/ServicePulse.Host/vue/test/preconditions/hasHeartbeatEndpoints.ts
src/ServicePulse.Host/vue/test/preconditions/index.ts
src/ServicePulse.Host/vue/test/preconditions/serviceControlWithMonitoring.ts

Rather than using a central stats object

Refactor Heartbeats menu and dashboard to use store

---

src/Custom.Build.props

Part of the work for https://github.com/Particular/PlatformInternals/issues/604

Add NuGetAuditMode = all and bump necessary versions

---

src/Frontend/src/composables/serviceNotifications.ts
src/Frontend/src/composables/serviceRedirects.ts

Follow through on https://github.com/Particular/ServicePulse/pull/1831

Use ternary and interpolation

---

src/Frontend/src/components/ExclamationMark.vue
src/Frontend/src/components/ItemsPerPage.vue
src/Frontend/src/components/TimeSince.vue
src/Frontend/src/components/configuration/RetryRedirectEdit.vue

Adding optional flags to all values initiazlied withDefaults in order to prevent warnings like the following:
More info here: 
- https://github.com/vuejs/vue/issues/7720#issuecomment-369172012

Adding an optional flag to prop values initialized withDefaults

---

src/Frontend/package-lock.json
src/Frontend/package.json
src/Frontend/src/App.vue
src/Frontend/src/components/configuration/EndpointConnection.vue
src/Frontend/src/mount.ts

This is part of https://github.com/Particular/ServicePulse/pull/1746, we are splitting the PR in smaller chunks.
The other one had issues when re-rendering different text with different code style in the same instance, the text would not update.
Before:
After:

New code editor

---

src/Frontend/src/components/ConditionalRender.vue
src/Frontend/src/components/DropDown.vue
src/Frontend/src/components/ExclamationMark.vue
src/Frontend/src/components/ServiceControlAvailable.vue

These components are used by #1746

A few new components

---

src/Frontend/src/components/failedmessages/MessageView.vue

Fixes https://github.com/Particular/ServicePulse/issues/1570

Filter message on endpoint address

---

src/Frontend/src/components/NoData.vue
src/Frontend/src/components/ResultsCount.vue
src/Frontend/src/components/heartbeats/EndpointInstances.vue
src/Frontend/src/components/heartbeats/HealthyEndpoints.vue

fix results count not showing and enable deletion of non-tracked endpoints

Elastic scale patch

---

src/Frontend/src/stores/ThroughputStore.ts
src/Frontend/src/views/throughputreport/transport.ts

Implementation of https://github.com/Particular/ServiceControl/issues/4254

Add PostgreSQL to Usage

---

src/Frontend/src/components/EventLogItem.vue
src/Frontend/src/components/configuration/HealthCheckNotifications.vue
src/Frontend/src/components/failedmessages/MessageList.vue

Few small improvements

---

src/Custom.Build.props

Remove redundant NuGetAuditMode setting

---

src/Frontend/src/components/configuration/MassTransitConnector.vue

change mass transit queue status display to have status indicator first

---

src/Frontend/package-lock.json
src/ServicePulse.Host/build.ps1

Making the build fail when there is transient CVEs for npm packages, as we do it with nuget packages.

Add a step on the build so it will fail when there is CVEs

---

src/ServicePulse/ConstantsFile.cs

Disable monitoringUrl also when ReverseProxy enabled

---

src/Frontend/src/components/messages/MessageView.vue

Reword the heading  of the retry popup dialog to a descriptive text

Reword the heading of the popup message in retry dialog

---

src/Frontend/src/components/messages2/SagaDiagram.spec.ts
src/Frontend/src/components/messages2/SagaDiagram.vue
src/Frontend/src/components/messages2/SagaDiagram/SagaDiagramParser.ts
src/Frontend/src/components/messages2/SagaDiagram/SagaHeader.vue
src/Frontend/src/composables/deliveryDelayParser.ts

This PR has the following minor bug fixes
- remove the unused message id url link and the related test
- Modify delivery delay parser to include days

Modify delivery delay parser to include days and remove unused message url link

---

src/Frontend/src/components/audit/AuditList.vue

This ensures we are not seeing this message as an error anymore

Treat ResolvedSuccessfully as a success

---

src/Frontend/src/components/messages2/SagaDiagram/SagaDiagramParser.ts
src/Frontend/src/components/messages2/SagaDiagram/SagaUpdateNode.vue

Display event icon if the intent is to publish in the initiation message

display event icon if the intent is publish

---

src/Frontend/src/components/messages2/SagaDiagram/SagaPluginNeeded.vue

fix copy feature in the install plugin message

fix copy feature in plugin message

---

src/Frontend/src/components/messages2/FlowDiagram/FlowDiagram.vue

Flow diagram overflow fix

---

src/ServicePulse/ServicePulse.csproj

Part of 
- https://github.com/Particular/PlatformInternals/issues/880

Update dotnet dependencies to 8.0.16

---

src/Frontend/src/components/audit/AuditList.vue
src/Frontend/src/components/audit/FiltersPanel.vue
src/Frontend/src/components/messages/FlowDiagram/FlowDiagram.vue
src/Frontend/src/components/messages/SequenceDiagram.vue
src/Frontend/src/composables/formatUtils.ts
src/Frontend/src/stores/AuditStore.ts
src/Frontend/src/views/AuditView.vue

Just removing .ts extension from imports

.ts is not required on import statements

---

src/Frontend/package-lock.json

Addresses https://github.com/advisories/GHSA-v6h2-p8h4-qcjw

Updated brace-expansion package to fix a vulnerability

---

src/ServicePulse/ServicePulse.csproj

Addresses https://github.com/Particular/ServicePulse/issues/2455

Jun 2025 .NET Runtime Update

---

src/Frontend/src/views/throughputreport/LegendNServiceBusEndpoint.vue
src/Frontend/src/views/throughputreport/LegendSendOnlyEndpoint.vue
src/Frontend/src/views/throughputreport/LegendTransactionalSessionProcessorEndpoint.vue

Part of 
- https://github.com/Particular/Website/pull/1618

Usage report legend docs redirects

---

src/Frontend/src/views/throughputreport/EndpointsView.vue

Part of 
- https://github.com/Particular/docs.particular.net/pull/7221

Link to endpoint type indicators documentation

---

.github/renovate.json5

Added NPM to the global config, along with PR labeling, so this is no longer required.

Remove Renovate file

---

src/Frontend/src/components/failedmessages/MessageList.vue

Brings in changes from https://github.com/Particular/ServicePulse/pull/2569 and closes https://github.com/Particular/ServicePulse/issues/2566

Update message view back button to return to previous page

---

src/Frontend/src/components/audit/FiltersPanel.vue

For https://github.com/Particular/ServicePulse/issues/2511

Updating link to filters documentation
